// Code generated by protoc-gen-easyrpc-kotlin. DO NOT EDIT.
package agentsdk

import easyrpc.*
import agent.v1.*
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow

class AgentServiceClient(private val t: Transport) {
  suspend fun health(req: HealthRequest): HealthResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/Health", body = req.toByteArray()))
    res.error?.let{ throw it }
    return HealthResponse.parseFrom(res.body)
  }

  suspend fun listSessions(req: ListSessionsRequest): ListSessionsResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/ListSessions", body = req.toByteArray()))
    res.error?.let{ throw it }
    return ListSessionsResponse.parseFrom(res.body)
  }

  suspend fun createSession(req: CreateSessionRequest): CreateSessionResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/CreateSession", body = req.toByteArray()))
    res.error?.let{ throw it }
    return CreateSessionResponse.parseFrom(res.body)
  }

  suspend fun getSession(req: GetSessionRequest): GetSessionResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/GetSession", body = req.toByteArray()))
    res.error?.let{ throw it }
    return GetSessionResponse.parseFrom(res.body)
  }

  suspend fun deleteSession(req: DeleteSessionRequest): DeleteSessionResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/DeleteSession", body = req.toByteArray()))
    res.error?.let{ throw it }
    return DeleteSessionResponse.parseFrom(res.body)
  }

  suspend fun listMessages(req: ListMessagesRequest): ListMessagesResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/ListMessages", body = req.toByteArray()))
    res.error?.let{ throw it }
    return ListMessagesResponse.parseFrom(res.body)
  }

  fun prompt(req: PromptRequest): Flow<PromptResponse> = flow {
    val st = t.openStream(Request(url = "/agent.v1.AgentService/Prompt", body = req.toByteArray()))
    while (true) { val p = st.recv() ?: break; emit(PromptResponse.parseFrom(p)) }
    st.lastError()?.let { throw it }
  }

  fun watchSession(req: WatchSessionRequest): Flow<WatchSessionResponse> = flow {
    val st = t.openStream(Request(url = "/agent.v1.AgentService/WatchSession", body = req.toByteArray()))
    while (true) { val p = st.recv() ?: break; emit(WatchSessionResponse.parseFrom(p)) }
    st.lastError()?.let { throw it }
  }

  fun watchSessions(req: WatchSessionsRequest): Flow<WatchSessionsResponse> = flow {
    val st = t.openStream(Request(url = "/agent.v1.AgentService/WatchSessions", body = req.toByteArray()))
    while (true) { val p = st.recv() ?: break; emit(WatchSessionsResponse.parseFrom(p)) }
    st.lastError()?.let { throw it }
  }

  suspend fun fork(req: ForkRequest): ForkResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/Fork", body = req.toByteArray()))
    res.error?.let{ throw it }
    return ForkResponse.parseFrom(res.body)
  }

  suspend fun rename(req: RenameRequest): RenameResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/Rename", body = req.toByteArray()))
    res.error?.let{ throw it }
    return RenameResponse.parseFrom(res.body)
  }

  suspend fun setModel(req: SetModelRequest): SetModelResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/SetModel", body = req.toByteArray()))
    res.error?.let{ throw it }
    return SetModelResponse.parseFrom(res.body)
  }

  suspend fun undo(req: UndoRequest): UndoResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/Undo", body = req.toByteArray()))
    res.error?.let{ throw it }
    return UndoResponse.parseFrom(res.body)
  }

  suspend fun state(req: StateRequest): StateResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/State", body = req.toByteArray()))
    res.error?.let{ throw it }
    return StateResponse.parseFrom(res.body)
  }

  suspend fun mailbox(req: MailboxRequest): MailboxResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/Mailbox", body = req.toByteArray()))
    res.error?.let{ throw it }
    return MailboxResponse.parseFrom(res.body)
  }

  suspend fun updateSettings(req: UpdateSettingsRequest): UpdateSettingsResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/UpdateSettings", body = req.toByteArray()))
    res.error?.let{ throw it }
    return UpdateSettingsResponse.parseFrom(res.body)
  }

  suspend fun interrupt(req: InterruptRequest): InterruptResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/Interrupt", body = req.toByteArray()))
    res.error?.let{ throw it }
    return InterruptResponse.parseFrom(res.body)
  }

  suspend fun compact(req: CompactRequest): CompactResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/Compact", body = req.toByteArray()))
    res.error?.let{ throw it }
    return CompactResponse.parseFrom(res.body)
  }

  suspend fun listProviders(req: ListProvidersRequest): ListProvidersResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/ListProviders", body = req.toByteArray()))
    res.error?.let{ throw it }
    return ListProvidersResponse.parseFrom(res.body)
  }

  suspend fun listProvidersCatalog(req: ListProvidersCatalogRequest): ListProvidersCatalogResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/ListProvidersCatalog", body = req.toByteArray()))
    res.error?.let{ throw it }
    return ListProvidersCatalogResponse.parseFrom(res.body)
  }

  suspend fun registerProvider(req: RegisterProviderRequest): RegisterProviderResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/RegisterProvider", body = req.toByteArray()))
    res.error?.let{ throw it }
    return RegisterProviderResponse.parseFrom(res.body)
  }

  suspend fun discoverGatewayModels(req: DiscoverGatewayModelsRequest): DiscoverGatewayModelsResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/DiscoverGatewayModels", body = req.toByteArray()))
    res.error?.let{ throw it }
    return DiscoverGatewayModelsResponse.parseFrom(res.body)
  }

  suspend fun deleteProvider(req: DeleteProviderRequest): DeleteProviderResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/DeleteProvider", body = req.toByteArray()))
    res.error?.let{ throw it }
    return DeleteProviderResponse.parseFrom(res.body)
  }

  suspend fun testProvider(req: TestProviderRequest): TestProviderResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/TestProvider", body = req.toByteArray()))
    res.error?.let{ throw it }
    return TestProviderResponse.parseFrom(res.body)
  }

  suspend fun listModels(req: ListModelsRequest): ListModelsResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/ListModels", body = req.toByteArray()))
    res.error?.let{ throw it }
    return ListModelsResponse.parseFrom(res.body)
  }

  suspend fun listPresets(req: ListPresetsRequest): ListPresetsResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/ListPresets", body = req.toByteArray()))
    res.error?.let{ throw it }
    return ListPresetsResponse.parseFrom(res.body)
  }

  suspend fun upsertPreset(req: UpsertPresetRequest): UpsertPresetResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/UpsertPreset", body = req.toByteArray()))
    res.error?.let{ throw it }
    return UpsertPresetResponse.parseFrom(res.body)
  }

  suspend fun deletePreset(req: DeletePresetRequest): DeletePresetResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/DeletePreset", body = req.toByteArray()))
    res.error?.let{ throw it }
    return DeletePresetResponse.parseFrom(res.body)
  }

  suspend fun previewPreset(req: PreviewPresetRequest): PreviewPresetResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/PreviewPreset", body = req.toByteArray()))
    res.error?.let{ throw it }
    return PreviewPresetResponse.parseFrom(res.body)
  }

  suspend fun getConfig(req: GetConfigRequest): GetConfigResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/GetConfig", body = req.toByteArray()))
    res.error?.let{ throw it }
    return GetConfigResponse.parseFrom(res.body)
  }

  suspend fun setConfig(req: SetConfigRequest): SetConfigResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/SetConfig", body = req.toByteArray()))
    res.error?.let{ throw it }
    return SetConfigResponse.parseFrom(res.body)
  }

  suspend fun listTools(req: ListToolsRequest): ListToolsResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/ListTools", body = req.toByteArray()))
    res.error?.let{ throw it }
    return ListToolsResponse.parseFrom(res.body)
  }

  suspend fun getToolConfig(req: GetToolConfigRequest): GetToolConfigResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/GetToolConfig", body = req.toByteArray()))
    res.error?.let{ throw it }
    return GetToolConfigResponse.parseFrom(res.body)
  }

  suspend fun setToolConfig(req: SetToolConfigRequest): SetToolConfigResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/SetToolConfig", body = req.toByteArray()))
    res.error?.let{ throw it }
    return SetToolConfigResponse.parseFrom(res.body)
  }

  suspend fun setExtensionConfig(req: SetExtensionConfigRequest): SetExtensionConfigResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/SetExtensionConfig", body = req.toByteArray()))
    res.error?.let{ throw it }
    return SetExtensionConfigResponse.parseFrom(res.body)
  }

  suspend fun uploadFile(req: UploadFileRequest): UploadFileResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/UploadFile", body = req.toByteArray()))
    res.error?.let{ throw it }
    return UploadFileResponse.parseFrom(res.body)
  }

  suspend fun ingestFile(req: IngestFileRequest): IngestFileResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/IngestFile", body = req.toByteArray()))
    res.error?.let{ throw it }
    return IngestFileResponse.parseFrom(res.body)
  }

  suspend fun getFile(req: GetFileRequest): GetFileResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/GetFile", body = req.toByteArray()))
    res.error?.let{ throw it }
    return GetFileResponse.parseFrom(res.body)
  }

  suspend fun getFileMeta(req: GetFileMetaRequest): GetFileMetaResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/GetFileMeta", body = req.toByteArray()))
    res.error?.let{ throw it }
    return GetFileMetaResponse.parseFrom(res.body)
  }

  suspend fun getAgentConfig(req: GetAgentConfigRequest): GetAgentConfigResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/GetAgentConfig", body = req.toByteArray()))
    res.error?.let{ throw it }
    return GetAgentConfigResponse.parseFrom(res.body)
  }

}