// Code generated by protoc-gen-easyrpc-kotlin. DO NOT EDIT.
package agentsdk

import easyrpc.*
import agent.v1.*
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow

class AdminServiceClient(private val t: Transport) {
  suspend fun listTenants(req: ListTenantsRequest): ListTenantsResponse {
    val res = t.send(Request(url = "/agent.v1.AdminService/ListTenants", body = req.toByteArray()))
    res.error?.let{ throw it }
    return ListTenantsResponse.parseFrom(res.body)
  }

  suspend fun createTenant(req: CreateTenantRequest): CreateTenantResponse {
    val res = t.send(Request(url = "/agent.v1.AdminService/CreateTenant", body = req.toByteArray()))
    res.error?.let{ throw it }
    return CreateTenantResponse.parseFrom(res.body)
  }

  suspend fun updateTenant(req: UpdateTenantRequest): UpdateTenantResponse {
    val res = t.send(Request(url = "/agent.v1.AdminService/UpdateTenant", body = req.toByteArray()))
    res.error?.let{ throw it }
    return UpdateTenantResponse.parseFrom(res.body)
  }

  suspend fun deleteTenant(req: DeleteTenantRequest): DeleteTenantResponse {
    val res = t.send(Request(url = "/agent.v1.AdminService/DeleteTenant", body = req.toByteArray()))
    res.error?.let{ throw it }
    return DeleteTenantResponse.parseFrom(res.body)
  }

  suspend fun issueTenantToken(req: IssueTenantTokenRequest): IssueTenantTokenResponse {
    val res = t.send(Request(url = "/agent.v1.AdminService/IssueTenantToken", body = req.toByteArray()))
    res.error?.let{ throw it }
    return IssueTenantTokenResponse.parseFrom(res.body)
  }

  suspend fun listTenantTokens(req: ListTenantTokensRequest): ListTenantTokensResponse {
    val res = t.send(Request(url = "/agent.v1.AdminService/ListTenantTokens", body = req.toByteArray()))
    res.error?.let{ throw it }
    return ListTenantTokensResponse.parseFrom(res.body)
  }

  suspend fun revokeTenantToken(req: RevokeTenantTokenRequest): RevokeTenantTokenResponse {
    val res = t.send(Request(url = "/agent.v1.AdminService/RevokeTenantToken", body = req.toByteArray()))
    res.error?.let{ throw it }
    return RevokeTenantTokenResponse.parseFrom(res.body)
  }

  suspend fun rotateTenantToken(req: RotateTenantTokenRequest): RotateTenantTokenResponse {
    val res = t.send(Request(url = "/agent.v1.AdminService/RotateTenantToken", body = req.toByteArray()))
    res.error?.let{ throw it }
    return RotateTenantTokenResponse.parseFrom(res.body)
  }

}