// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto
// Protobuf Java Version: 4.36.1

package agent.v1;

/**
 * Protobuf type {@code agent.v1.CatalogProvider}
 */
@com.google.protobuf.Generated
public  final class CatalogProvider extends
    com.google.protobuf.GeneratedMessageLite<
        CatalogProvider, CatalogProvider.Builder> implements
    // @@protoc_insertion_point(message_implements:agent.v1.CatalogProvider)
    CatalogProviderOrBuilder {
  private CatalogProvider() {
    id_ = "";
    name_ = "";
    api_ = "";
    npm_ = "";
    env_ = emptyProtobufList();
    models_ = emptyProtobufList();
  }
  public interface ModelsEntryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:agent.v1.CatalogProvider.ModelsEntry)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string key = 1 [json_name = "key"];</code>
     * @return The key.
     */
    java.lang.String getKey();
    /**
     * <code>string key = 1 [json_name = "key"];</code>
     * @return The bytes for key.
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>.google.protobuf.Value value = 2 [json_name = "value"];</code>
     * @return Whether the value field is set.
     */
    boolean hasValue();
    /**
     * <code>.google.protobuf.Value value = 2 [json_name = "value"];</code>
     * @return The value.
     */
    com.google.protobuf.Value getValue();
  }
  /**
   * Protobuf type {@code agent.v1.CatalogProvider.ModelsEntry}
   */
  public  static final class ModelsEntry extends
      com.google.protobuf.GeneratedMessageLite<
          ModelsEntry, ModelsEntry.Builder> implements
      // @@protoc_insertion_point(message_implements:agent.v1.CatalogProvider.ModelsEntry)
      ModelsEntryOrBuilder {
    private ModelsEntry() {
      key_ = "";
    }
    private int bitField0_;
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.String key_;
    /**
     * <code>string key = 1 [json_name = "key"];</code>
     * @return The key.
     */
    @java.lang.Override
    public java.lang.String getKey() {
      return key_;
    }
    /**
     * <code>string key = 1 [json_name = "key"];</code>
     * @return The bytes for key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeyBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(key_);
    }
    /**
     * <code>string key = 1 [json_name = "key"];</code>
     * @param value The key to set.
     */
    private void setKey(
        java.lang.String value) {
      java.util.Objects.requireNonNull(value);

      key_ = value;
    }
    /**
     * <code>string key = 1 [json_name = "key"];</code>
     */
    private void clearKey() {

      key_ = getDefaultInstance().getKey();
    }
    /**
     * <code>string key = 1 [json_name = "key"];</code>
     * @param value The bytes for key to set.
     */
    private void setKeyBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      key_ = value.toStringUtf8();

    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private com.google.protobuf.Value value_;
    /**
     * <code>.google.protobuf.Value value = 2 [json_name = "value"];</code>
     */
    @java.lang.Override
    public boolean hasValue() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Value value = 2 [json_name = "value"];</code>
     */
    @java.lang.Override
    public com.google.protobuf.Value getValue() {
      return value_ == null ? com.google.protobuf.Value.getDefaultInstance() : value_;
    }
    /**
     * <code>.google.protobuf.Value value = 2 [json_name = "value"];</code>
     */
    private void setValue(com.google.protobuf.Value value) {
      java.util.Objects.requireNonNull(value);
      value_ = value;
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>.google.protobuf.Value value = 2 [json_name = "value"];</code>
     */
    @java.lang.SuppressWarnings("ReferenceEquality")
    private void mergeValue(com.google.protobuf.Value value) {
      java.util.Objects.requireNonNull(value);
      if (value_ != null &&
          value_ != com.google.protobuf.Value.getDefaultInstance()) {
        value_ =
          com.google.protobuf.Value.newBuilder(value_).mergeFrom(value).buildPartial();
      } else {
        value_ = value;
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>.google.protobuf.Value value = 2 [json_name = "value"];</code>
     */
    private void clearValue() {
      value_ = null;
      bitField0_ = (bitField0_ & ~0x00000001);
    }

    public static agent.v1.CatalogProvider.ModelsEntry parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static agent.v1.CatalogProvider.ModelsEntry parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static agent.v1.CatalogProvider.ModelsEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static agent.v1.CatalogProvider.ModelsEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static agent.v1.CatalogProvider.ModelsEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static agent.v1.CatalogProvider.ModelsEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static agent.v1.CatalogProvider.ModelsEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static agent.v1.CatalogProvider.ModelsEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static agent.v1.CatalogProvider.ModelsEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static agent.v1.CatalogProvider.ModelsEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static agent.v1.CatalogProvider.ModelsEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static agent.v1.CatalogProvider.ModelsEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(agent.v1.CatalogProvider.ModelsEntry prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code agent.v1.CatalogProvider.ModelsEntry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          agent.v1.CatalogProvider.ModelsEntry, Builder> implements
        // @@protoc_insertion_point(builder_implements:agent.v1.CatalogProvider.ModelsEntry)
        agent.v1.CatalogProvider.ModelsEntryOrBuilder {
      // Construct using agent.v1.CatalogProvider.ModelsEntry.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string key = 1 [json_name = "key"];</code>
       * @return The key.
       */
      @java.lang.Override
      public java.lang.String getKey() {
        return instance.getKey();
      }
      /**
       * <code>string key = 1 [json_name = "key"];</code>
       * @return The bytes for key.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getKeyBytes() {
        return instance.getKeyBytes();
      }
      /**
       * <code>string key = 1 [json_name = "key"];</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(
          java.lang.String value) {
        copyOnWrite();
        instance.setKey(value);
        return this;
      }
      /**
       * <code>string key = 1 [json_name = "key"];</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        copyOnWrite();
        instance.clearKey();
        return this;
      }
      /**
       * <code>string key = 1 [json_name = "key"];</code>
       * @param value The bytes for key to set.
       * @return This builder for chaining.
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setKeyBytes(value);
        return this;
      }

      /**
       * <code>.google.protobuf.Value value = 2 [json_name = "value"];</code>
       */
      @java.lang.Override
      public boolean hasValue() {
        return instance.hasValue();
      }
      /**
       * <code>.google.protobuf.Value value = 2 [json_name = "value"];</code>
       */
      @java.lang.Override
      public com.google.protobuf.Value getValue() {
        return instance.getValue();
      }
      /**
       * <code>.google.protobuf.Value value = 2 [json_name = "value"];</code>
       */
      public Builder setValue(com.google.protobuf.Value value) {
        copyOnWrite();
        instance.setValue(value);
        return this;
        }
      /**
       * <code>.google.protobuf.Value value = 2 [json_name = "value"];</code>
       */
      public Builder setValue(
          com.google.protobuf.Value.Builder builderForValue) {
        copyOnWrite();
        instance.setValue(builderForValue.build());
        return this;
      }
      /**
       * <code>.google.protobuf.Value value = 2 [json_name = "value"];</code>
       */
      public Builder mergeValue(com.google.protobuf.Value value) {
        copyOnWrite();
        instance.mergeValue(value);
        return this;
      }
      /**
       * <code>.google.protobuf.Value value = 2 [json_name = "value"];</code>
       */
      public Builder clearValue() {  copyOnWrite();
        instance.clearValue();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:agent.v1.CatalogProvider.ModelsEntry)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new agent.v1.CatalogProvider.ModelsEntry();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "key_",
              "value_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u1009" +
                "\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<agent.v1.CatalogProvider.ModelsEntry> parser = PARSER;
          if (parser == null) {
            synchronized (agent.v1.CatalogProvider.ModelsEntry.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<agent.v1.CatalogProvider.ModelsEntry>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:agent.v1.CatalogProvider.ModelsEntry)
    private static final agent.v1.CatalogProvider.ModelsEntry DEFAULT_INSTANCE;
    static {
      ModelsEntry defaultInstance = new ModelsEntry();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ModelsEntry.class, defaultInstance);
    }

    public static agent.v1.CatalogProvider.ModelsEntry getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ModelsEntry> PARSER;

    public static com.google.protobuf.Parser<ModelsEntry> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public static final int ID_FIELD_NUMBER = 1;
  private java.lang.String id_;
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    return id_;
  }
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(id_);
  }
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @param value The id to set.
   */
  private void setId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    id_ = value;
  }
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   */
  private void clearId() {

    id_ = getDefaultInstance().getId();
  }
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @param value The bytes for id to set.
   */
  private void setIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    id_ = value.toStringUtf8();

  }

  public static final int NAME_FIELD_NUMBER = 2;
  private java.lang.String name_;
  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    return name_;
  }
  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(name_);
  }
  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @param value The name to set.
   */
  private void setName(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    name_ = value;
  }
  /**
   * <code>string name = 2 [json_name = "name"];</code>
   */
  private void clearName() {

    name_ = getDefaultInstance().getName();
  }
  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @param value The bytes for name to set.
   */
  private void setNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    name_ = value.toStringUtf8();

  }

  public static final int API_FIELD_NUMBER = 3;
  private java.lang.String api_;
  /**
   * <code>string api = 3 [json_name = "api"];</code>
   * @return The api.
   */
  @java.lang.Override
  public java.lang.String getApi() {
    return api_;
  }
  /**
   * <code>string api = 3 [json_name = "api"];</code>
   * @return The bytes for api.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getApiBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(api_);
  }
  /**
   * <code>string api = 3 [json_name = "api"];</code>
   * @param value The api to set.
   */
  private void setApi(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    api_ = value;
  }
  /**
   * <code>string api = 3 [json_name = "api"];</code>
   */
  private void clearApi() {

    api_ = getDefaultInstance().getApi();
  }
  /**
   * <code>string api = 3 [json_name = "api"];</code>
   * @param value The bytes for api to set.
   */
  private void setApiBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    api_ = value.toStringUtf8();

  }

  public static final int NPM_FIELD_NUMBER = 4;
  private java.lang.String npm_;
  /**
   * <code>string npm = 4 [json_name = "npm"];</code>
   * @return The npm.
   */
  @java.lang.Override
  public java.lang.String getNpm() {
    return npm_;
  }
  /**
   * <code>string npm = 4 [json_name = "npm"];</code>
   * @return The bytes for npm.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNpmBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(npm_);
  }
  /**
   * <code>string npm = 4 [json_name = "npm"];</code>
   * @param value The npm to set.
   */
  private void setNpm(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    npm_ = value;
  }
  /**
   * <code>string npm = 4 [json_name = "npm"];</code>
   */
  private void clearNpm() {

    npm_ = getDefaultInstance().getNpm();
  }
  /**
   * <code>string npm = 4 [json_name = "npm"];</code>
   * @param value The bytes for npm to set.
   */
  private void setNpmBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    npm_ = value.toStringUtf8();

  }

  public static final int ENV_FIELD_NUMBER = 5;
  private com.google.protobuf.Internal.ProtobufList<java.lang.String> env_;
  /**
   * <code>repeated string env = 5 [json_name = "env"];</code>
   * @return A list containing the env.
   */
  @java.lang.Override
  public java.util.List<java.lang.String> getEnvList() {
    return env_;
  }
  /**
   * <code>repeated string env = 5 [json_name = "env"];</code>
   * @return The count of env.
   */
  @java.lang.Override
  public int getEnvCount() {
    return env_.size();
  }
  /**
   * <code>repeated string env = 5 [json_name = "env"];</code>
   * @param index The index of the element to return.
   * @return The env at the given index.
   */
  @java.lang.Override
  public java.lang.String getEnv(int index) {
    return env_.get(index);
  }
  /**
   * <code>repeated string env = 5 [json_name = "env"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the env at the given index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEnvBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        env_.get(index));
  }
  private void ensureEnvIsMutable() {
    com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
        env_;  if (!tmp.isModifiable()) {
      env_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <code>repeated string env = 5 [json_name = "env"];</code>
   * @param index The index to set the value at.
   * @param value The env to set.
   */
  private void setEnv(
      int index, java.lang.String value) {
    java.util.Objects.requireNonNull(value);
    ensureEnvIsMutable();
    env_.set(index, value);
  }
  /**
   * <code>repeated string env = 5 [json_name = "env"];</code>
   * @param value The env to add.
   */
  private void addEnv(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);
    ensureEnvIsMutable();
    env_.add(value);
  }
  /**
   * <code>repeated string env = 5 [json_name = "env"];</code>
   * @param values The env to add.
   */
  private void addAllEnv(
      java.lang.Iterable<java.lang.String> values) {
    ensureEnvIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, env_);
  }
  /**
   * <code>repeated string env = 5 [json_name = "env"];</code>
   */
  private void clearEnv() {
    env_ = emptyProtobufList();
  }
  /**
   * <code>repeated string env = 5 [json_name = "env"];</code>
   * @param value The bytes of the env to add.
   */
  private void addEnvBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ensureEnvIsMutable();
    env_.add(value.toStringUtf8());
  }

  public static final int MODELS_FIELD_NUMBER = 6;
  private com.google.protobuf.Internal.ProtobufList<agent.v1.CatalogProvider.ModelsEntry> models_;
  /**
   * <code>repeated .agent.v1.CatalogProvider.ModelsEntry models = 6 [json_name = "models"];</code>
   */
  @java.lang.Override
  public java.util.List<agent.v1.CatalogProvider.ModelsEntry> getModelsList() {
    return models_;
  }
  /**
   * <code>repeated .agent.v1.CatalogProvider.ModelsEntry models = 6 [json_name = "models"];</code>
   */
  public java.util.List<? extends agent.v1.CatalogProvider.ModelsEntryOrBuilder> 
      getModelsOrBuilderList() {
    return models_;
  }
  /**
   * <code>repeated .agent.v1.CatalogProvider.ModelsEntry models = 6 [json_name = "models"];</code>
   */
  @java.lang.Override
  public int getModelsCount() {
    return models_.size();
  }
  /**
   * <code>repeated .agent.v1.CatalogProvider.ModelsEntry models = 6 [json_name = "models"];</code>
   */
  @java.lang.Override
  public agent.v1.CatalogProvider.ModelsEntry getModels(int index) {
    return models_.get(index);
  }
  /**
   * <code>repeated .agent.v1.CatalogProvider.ModelsEntry models = 6 [json_name = "models"];</code>
   */
  public agent.v1.CatalogProvider.ModelsEntryOrBuilder getModelsOrBuilder(
      int index) {
    return models_.get(index);
  }
  private void ensureModelsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<agent.v1.CatalogProvider.ModelsEntry> tmp = models_;
    if (!tmp.isModifiable()) {
      models_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .agent.v1.CatalogProvider.ModelsEntry models = 6 [json_name = "models"];</code>
   */
  private void setModels(
      int index, agent.v1.CatalogProvider.ModelsEntry value) {
    java.util.Objects.requireNonNull(value);
    ensureModelsIsMutable();
    models_.set(index, value);
  }
  /**
   * <code>repeated .agent.v1.CatalogProvider.ModelsEntry models = 6 [json_name = "models"];</code>
   */
  private void addModels(agent.v1.CatalogProvider.ModelsEntry value) {
    java.util.Objects.requireNonNull(value);
    ensureModelsIsMutable();
    models_.add(value);
  }
  /**
   * <code>repeated .agent.v1.CatalogProvider.ModelsEntry models = 6 [json_name = "models"];</code>
   */
  private void addModels(
      int index, agent.v1.CatalogProvider.ModelsEntry value) {
    java.util.Objects.requireNonNull(value);
    ensureModelsIsMutable();
    models_.add(index, value);
  }
  /**
   * <code>repeated .agent.v1.CatalogProvider.ModelsEntry models = 6 [json_name = "models"];</code>
   */
  private void addAllModels(
      java.lang.Iterable<? extends agent.v1.CatalogProvider.ModelsEntry> values) {
    ensureModelsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, models_);
  }
  /**
   * <code>repeated .agent.v1.CatalogProvider.ModelsEntry models = 6 [json_name = "models"];</code>
   */
  private void clearModels() {
    models_ = emptyProtobufList();
  }
  /**
   * <code>repeated .agent.v1.CatalogProvider.ModelsEntry models = 6 [json_name = "models"];</code>
   */
  private void removeModels(int index) {
    ensureModelsIsMutable();
    models_.remove(index);
  }

  public static agent.v1.CatalogProvider parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static agent.v1.CatalogProvider parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static agent.v1.CatalogProvider parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static agent.v1.CatalogProvider parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static agent.v1.CatalogProvider parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static agent.v1.CatalogProvider parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static agent.v1.CatalogProvider parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static agent.v1.CatalogProvider parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static agent.v1.CatalogProvider parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static agent.v1.CatalogProvider parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static agent.v1.CatalogProvider parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static agent.v1.CatalogProvider parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(agent.v1.CatalogProvider prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code agent.v1.CatalogProvider}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        agent.v1.CatalogProvider, Builder> implements
      // @@protoc_insertion_point(builder_implements:agent.v1.CatalogProvider)
      agent.v1.CatalogProviderOrBuilder {
    // Construct using agent.v1.CatalogProvider.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      return instance.getId();
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      return instance.getIdBytes();
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      copyOnWrite();
      instance.setId(value);
      return this;
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      copyOnWrite();
      instance.clearId();
      return this;
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setIdBytes(value);
      return this;
    }

    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      return instance.getName();
    }
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return instance.getNameBytes();
    }
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      copyOnWrite();
      instance.setName(value);
      return this;
    }
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      copyOnWrite();
      instance.clearName();
      return this;
    }
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNameBytes(value);
      return this;
    }

    /**
     * <code>string api = 3 [json_name = "api"];</code>
     * @return The api.
     */
    @java.lang.Override
    public java.lang.String getApi() {
      return instance.getApi();
    }
    /**
     * <code>string api = 3 [json_name = "api"];</code>
     * @return The bytes for api.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getApiBytes() {
      return instance.getApiBytes();
    }
    /**
     * <code>string api = 3 [json_name = "api"];</code>
     * @param value The api to set.
     * @return This builder for chaining.
     */
    public Builder setApi(
        java.lang.String value) {
      copyOnWrite();
      instance.setApi(value);
      return this;
    }
    /**
     * <code>string api = 3 [json_name = "api"];</code>
     * @return This builder for chaining.
     */
    public Builder clearApi() {
      copyOnWrite();
      instance.clearApi();
      return this;
    }
    /**
     * <code>string api = 3 [json_name = "api"];</code>
     * @param value The bytes for api to set.
     * @return This builder for chaining.
     */
    public Builder setApiBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setApiBytes(value);
      return this;
    }

    /**
     * <code>string npm = 4 [json_name = "npm"];</code>
     * @return The npm.
     */
    @java.lang.Override
    public java.lang.String getNpm() {
      return instance.getNpm();
    }
    /**
     * <code>string npm = 4 [json_name = "npm"];</code>
     * @return The bytes for npm.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNpmBytes() {
      return instance.getNpmBytes();
    }
    /**
     * <code>string npm = 4 [json_name = "npm"];</code>
     * @param value The npm to set.
     * @return This builder for chaining.
     */
    public Builder setNpm(
        java.lang.String value) {
      copyOnWrite();
      instance.setNpm(value);
      return this;
    }
    /**
     * <code>string npm = 4 [json_name = "npm"];</code>
     * @return This builder for chaining.
     */
    public Builder clearNpm() {
      copyOnWrite();
      instance.clearNpm();
      return this;
    }
    /**
     * <code>string npm = 4 [json_name = "npm"];</code>
     * @param value The bytes for npm to set.
     * @return This builder for chaining.
     */
    public Builder setNpmBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNpmBytes(value);
      return this;
    }

    /**
     * <code>repeated string env = 5 [json_name = "env"];</code>
     * @return A list containing the env.
     */
    @java.lang.Override
    public java.util.List<java.lang.String>
        getEnvList() {
      return java.util.Collections.unmodifiableList(
          instance.getEnvList());
    }
    /**
     * <code>repeated string env = 5 [json_name = "env"];</code>
     * @return The count of env.
     */
    @java.lang.Override
    public int getEnvCount() {
      return instance.getEnvCount();
    }
    /**
     * <code>repeated string env = 5 [json_name = "env"];</code>
     * @param index The index of the element to return.
     * @return The env at the given index.
     */
    @java.lang.Override
    public java.lang.String getEnv(int index) {
      return instance.getEnv(index);
    }
    /**
     * <code>repeated string env = 5 [json_name = "env"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the env at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEnvBytes(int index) {
      return instance.getEnvBytes(index);
    }
    /**
     * <code>repeated string env = 5 [json_name = "env"];</code>
     * @param index The index to set the value at.
     * @param value The env to set.
     * @return This builder for chaining.
     */
    public Builder setEnv(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setEnv(index, value);
      return this;
    }
    /**
     * <code>repeated string env = 5 [json_name = "env"];</code>
     * @param value The env to add.
     * @return This builder for chaining.
     */
    public Builder addEnv(
        java.lang.String value) {
      copyOnWrite();
      instance.addEnv(value);
      return this;
    }
    /**
     * <code>repeated string env = 5 [json_name = "env"];</code>
     * @param values The env to add.
     * @return This builder for chaining.
     */
    public Builder addAllEnv(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllEnv(values);
      return this;
    }
    /**
     * <code>repeated string env = 5 [json_name = "env"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEnv() {
      copyOnWrite();
      instance.clearEnv();
      return this;
    }
    /**
     * <code>repeated string env = 5 [json_name = "env"];</code>
     * @param value The bytes of the env to add.
     * @return This builder for chaining.
     */
    public Builder addEnvBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addEnvBytes(value);
      return this;
    }

    /**
     * <code>repeated .agent.v1.CatalogProvider.ModelsEntry models = 6 [json_name = "models"];</code>
     */
    @java.lang.Override
    public java.util.List<agent.v1.CatalogProvider.ModelsEntry> getModelsList() {
      return java.util.Collections.unmodifiableList(
          instance.getModelsList());
    }
    /**
     * <code>repeated .agent.v1.CatalogProvider.ModelsEntry models = 6 [json_name = "models"];</code>
     */
    @java.lang.Override
    public int getModelsCount() {
      return instance.getModelsCount();
    }/**
     * <code>repeated .agent.v1.CatalogProvider.ModelsEntry models = 6 [json_name = "models"];</code>
     */
    @java.lang.Override
    public agent.v1.CatalogProvider.ModelsEntry getModels(int index) {
      return instance.getModels(index);
    }
    /**
     * <code>repeated .agent.v1.CatalogProvider.ModelsEntry models = 6 [json_name = "models"];</code>
     */
    public Builder setModels(
        int index, agent.v1.CatalogProvider.ModelsEntry value) {
      copyOnWrite();
      instance.setModels(index, value);
      return this;
    }
    /**
     * <code>repeated .agent.v1.CatalogProvider.ModelsEntry models = 6 [json_name = "models"];</code>
     */
    public Builder setModels(
        int index, agent.v1.CatalogProvider.ModelsEntry.Builder builderForValue) {
      copyOnWrite();
      instance.setModels(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .agent.v1.CatalogProvider.ModelsEntry models = 6 [json_name = "models"];</code>
     */
    public Builder addModels(agent.v1.CatalogProvider.ModelsEntry value) {
      copyOnWrite();
      instance.addModels(value);
      return this;
    }
    /**
     * <code>repeated .agent.v1.CatalogProvider.ModelsEntry models = 6 [json_name = "models"];</code>
     */
    public Builder addModels(
        int index, agent.v1.CatalogProvider.ModelsEntry value) {
      copyOnWrite();
      instance.addModels(index, value);
      return this;
    }
    /**
     * <code>repeated .agent.v1.CatalogProvider.ModelsEntry models = 6 [json_name = "models"];</code>
     */
    public Builder addModels(
        agent.v1.CatalogProvider.ModelsEntry.Builder builderForValue) {
      copyOnWrite();
      instance.addModels(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .agent.v1.CatalogProvider.ModelsEntry models = 6 [json_name = "models"];</code>
     */
    public Builder addModels(
        int index, agent.v1.CatalogProvider.ModelsEntry.Builder builderForValue) {
      copyOnWrite();
      instance.addModels(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .agent.v1.CatalogProvider.ModelsEntry models = 6 [json_name = "models"];</code>
     */
    public Builder addAllModels(
        java.lang.Iterable<? extends agent.v1.CatalogProvider.ModelsEntry> values) {
      copyOnWrite();
      instance.addAllModels(values);
      return this;
    }
    /**
     * <code>repeated .agent.v1.CatalogProvider.ModelsEntry models = 6 [json_name = "models"];</code>
     */
    public Builder clearModels() {
      copyOnWrite();
      instance.clearModels();
      return this;
    }
    /**
     * <code>repeated .agent.v1.CatalogProvider.ModelsEntry models = 6 [json_name = "models"];</code>
     */
    public Builder removeModels(int index) {
      copyOnWrite();
      instance.removeModels(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:agent.v1.CatalogProvider)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new agent.v1.CatalogProvider();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "id_",
            "name_",
            "api_",
            "npm_",
            "env_",
            "models_",
            agent.v1.CatalogProvider.ModelsEntry.class,
          };
          java.lang.String info =
              "\u0000\u0006\u0000\u0000\u0001\u0006\u0006\u0000\u0002\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208\u0004\u0208\u0005\u021a\u0006\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<agent.v1.CatalogProvider> parser = PARSER;
        if (parser == null) {
          synchronized (agent.v1.CatalogProvider.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<agent.v1.CatalogProvider>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:agent.v1.CatalogProvider)
  private static final agent.v1.CatalogProvider DEFAULT_INSTANCE;
  static {
    CatalogProvider defaultInstance = new CatalogProvider();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      CatalogProvider.class, defaultInstance);
  }

  public static agent.v1.CatalogProvider getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<CatalogProvider> PARSER;

  public static com.google.protobuf.Parser<CatalogProvider> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

