// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package agent.v1;

@kotlin.jvm.JvmName("-initializecatalogProvider")
public inline fun catalogProvider(block: agent.v1.CatalogProviderKt.Dsl.() -> kotlin.Unit): agent.v1.CatalogProvider =
  agent.v1.CatalogProviderKt.Dsl._create(agent.v1.CatalogProvider.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `agent.v1.CatalogProvider`
 */
public object CatalogProviderKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: agent.v1.CatalogProvider.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: agent.v1.CatalogProvider.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): agent.v1.CatalogProvider = _builder.build()

    /**
     * `string id = 1 [json_name = "id"];`
     */
    public var id: kotlin.String
      @kotlin.jvm.JvmName("getId")
        get() = _builder.id
      @kotlin.jvm.JvmName("setId")
        set(value) {
        _builder.id = value
      }
    /**
     * `string id = 1 [json_name = "id"];`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `string name = 2 [json_name = "name"];`
     */
    public var name: kotlin.String
      @kotlin.jvm.JvmName("getName")
        get() = _builder.name
      @kotlin.jvm.JvmName("setName")
        set(value) {
        _builder.name = value
      }
    /**
     * `string name = 2 [json_name = "name"];`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `string api = 3 [json_name = "api"];`
     */
    public var api: kotlin.String
      @kotlin.jvm.JvmName("getApi")
        get() = _builder.api
      @kotlin.jvm.JvmName("setApi")
        set(value) {
        _builder.api = value
      }
    /**
     * `string api = 3 [json_name = "api"];`
     */
    public fun clearApi() {
      _builder.clearApi()
    }

    /**
     * `string npm = 4 [json_name = "npm"];`
     */
    public var npm: kotlin.String
      @kotlin.jvm.JvmName("getNpm")
        get() = _builder.npm
      @kotlin.jvm.JvmName("setNpm")
        set(value) {
        _builder.npm = value
      }
    /**
     * `string npm = 4 [json_name = "npm"];`
     */
    public fun clearNpm() {
      _builder.clearNpm()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class EnvProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string env = 5 [json_name = "env"];`
     * @return A list containing the env.
     */
    public val env: com.google.protobuf.kotlin.DslList<kotlin.String, EnvProxy>
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.envList
      )
    /**
     * `repeated string env = 5 [json_name = "env"];`
     * @param value The env to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addEnv")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, EnvProxy>.add(value: kotlin.String) {
      _builder.addEnv(value)
    }
    /**
     * `repeated string env = 5 [json_name = "env"];`
     * @param value The env to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignEnv")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, EnvProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string env = 5 [json_name = "env"];`
     * @param values The env to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllEnv")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, EnvProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllEnv(values)
    }
    /**
     * `repeated string env = 5 [json_name = "env"];`
     * @param values The env to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllEnv")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, EnvProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string env = 5 [json_name = "env"];`
     * @param index The index to set the value at.
     * @param value The env to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setEnv")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, EnvProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setEnv(index, value)
    }/**
     * `repeated string env = 5 [json_name = "env"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setEnv")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, EnvProxy>.clear() {
      _builder.clearEnv()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ModelsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .agent.v1.CatalogProvider.ModelsEntry models = 6 [json_name = "models"];`
     */
     public val models: com.google.protobuf.kotlin.DslList<agent.v1.CatalogProvider.ModelsEntry, ModelsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.modelsList
      )
    /**
     * `repeated .agent.v1.CatalogProvider.ModelsEntry models = 6 [json_name = "models"];`
     * @param value The models to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addModels")
    public fun com.google.protobuf.kotlin.DslList<agent.v1.CatalogProvider.ModelsEntry, ModelsProxy>.add(value: agent.v1.CatalogProvider.ModelsEntry) {
      _builder.addModels(value)
    }
    /**
     * `repeated .agent.v1.CatalogProvider.ModelsEntry models = 6 [json_name = "models"];`
     * @param value The models to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignModels")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<agent.v1.CatalogProvider.ModelsEntry, ModelsProxy>.plusAssign(value: agent.v1.CatalogProvider.ModelsEntry) {
      add(value)
    }
    /**
     * `repeated .agent.v1.CatalogProvider.ModelsEntry models = 6 [json_name = "models"];`
     * @param values The models to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllModels")
    public fun com.google.protobuf.kotlin.DslList<agent.v1.CatalogProvider.ModelsEntry, ModelsProxy>.addAll(values: kotlin.collections.Iterable<agent.v1.CatalogProvider.ModelsEntry>) {
      _builder.addAllModels(values)
    }
    /**
     * `repeated .agent.v1.CatalogProvider.ModelsEntry models = 6 [json_name = "models"];`
     * @param values The models to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllModels")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<agent.v1.CatalogProvider.ModelsEntry, ModelsProxy>.plusAssign(values: kotlin.collections.Iterable<agent.v1.CatalogProvider.ModelsEntry>) {
      addAll(values)
    }
    /**
     * `repeated .agent.v1.CatalogProvider.ModelsEntry models = 6 [json_name = "models"];`
     * @param index The index to set the value at.
     * @param value The models to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setModels")
    public operator fun com.google.protobuf.kotlin.DslList<agent.v1.CatalogProvider.ModelsEntry, ModelsProxy>.set(index: kotlin.Int, value: agent.v1.CatalogProvider.ModelsEntry) {
      _builder.setModels(index, value)
    }
    /**
     * `repeated .agent.v1.CatalogProvider.ModelsEntry models = 6 [json_name = "models"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearModels")
    public fun com.google.protobuf.kotlin.DslList<agent.v1.CatalogProvider.ModelsEntry, ModelsProxy>.clear() {
      _builder.clearModels()
    }
  }
  @kotlin.jvm.JvmName("-initializemodelsEntry")
  public inline fun modelsEntry(block: agent.v1.CatalogProviderKt.ModelsEntryKt.Dsl.() -> kotlin.Unit): agent.v1.CatalogProvider.ModelsEntry =
    agent.v1.CatalogProviderKt.ModelsEntryKt.Dsl._create(agent.v1.CatalogProvider.ModelsEntry.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `agent.v1.CatalogProvider.ModelsEntry`
   */
  public object ModelsEntryKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: agent.v1.CatalogProvider.ModelsEntry.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: agent.v1.CatalogProvider.ModelsEntry.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): agent.v1.CatalogProvider.ModelsEntry = _builder.build()

      /**
       * `string key = 1 [json_name = "key"];`
       */
      public var key: kotlin.String
        @kotlin.jvm.JvmName("getKey")
          get() = _builder.key
        @kotlin.jvm.JvmName("setKey")
          set(value) {
          _builder.key = value
        }
      /**
       * `string key = 1 [json_name = "key"];`
       */
      public fun clearKey() {
        _builder.clearKey()
      }

      /**
       * `.google.protobuf.Value value = 2 [json_name = "value"];`
       */
      public var value: com.google.protobuf.Value
        @kotlin.jvm.JvmName("getValue")
          get() = _builder.value
        @kotlin.jvm.JvmName("setValue")
          set(value) {
          _builder.value = value
        }
      /**
       * `.google.protobuf.Value value = 2 [json_name = "value"];`
       */
      public fun clearValue() {
        _builder.clearValue()
      }
      /**
       * `.google.protobuf.Value value = 2 [json_name = "value"];`
       * @return Whether the value field is set.
       */
      public fun hasValue(): kotlin.Boolean {
        return _builder.hasValue()
      }

      public val ModelsEntryKt.Dsl.valueOrNull: com.google.protobuf.Value?
        get() = _builder.valueOrNull
    }
  }
}
public inline fun agent.v1.CatalogProvider.copy(block: `agent.v1`.CatalogProviderKt.Dsl.() -> kotlin.Unit): agent.v1.CatalogProvider =
  `agent.v1`.CatalogProviderKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public inline fun agent.v1.CatalogProvider.ModelsEntry.copy(block: `agent.v1`.CatalogProviderKt.ModelsEntryKt.Dsl.() -> kotlin.Unit): agent.v1.CatalogProvider.ModelsEntry =
  `agent.v1`.CatalogProviderKt.ModelsEntryKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val agent.v1.CatalogProvider.ModelsEntryOrBuilder.valueOrNull: com.google.protobuf.Value?
  get() = if (hasValue()) getValue() else null

