// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package agent.v1;

@kotlin.jvm.JvmName("-initializecreateTenantResponse")
public inline fun createTenantResponse(block: agent.v1.CreateTenantResponseKt.Dsl.() -> kotlin.Unit): agent.v1.CreateTenantResponse =
  agent.v1.CreateTenantResponseKt.Dsl._create(agent.v1.CreateTenantResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `agent.v1.CreateTenantResponse`
 */
public object CreateTenantResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: agent.v1.CreateTenantResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: agent.v1.CreateTenantResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): agent.v1.CreateTenantResponse = _builder.build()

    /**
     * `.agent.v1.Tenant tenant = 1 [json_name = "tenant"];`
     */
    public var tenant: agent.v1.Tenant
      @kotlin.jvm.JvmName("getTenant")
        get() = _builder.tenant
      @kotlin.jvm.JvmName("setTenant")
        set(value) {
        _builder.tenant = value
      }
    /**
     * `.agent.v1.Tenant tenant = 1 [json_name = "tenant"];`
     */
    public fun clearTenant() {
      _builder.clearTenant()
    }
    /**
     * `.agent.v1.Tenant tenant = 1 [json_name = "tenant"];`
     * @return Whether the tenant field is set.
     */
    public fun hasTenant(): kotlin.Boolean {
      return _builder.hasTenant()
    }

    public val CreateTenantResponseKt.Dsl.tenantOrNull: agent.v1.Tenant?
      get() = _builder.tenantOrNull

    /**
     * `string token = 2 [json_name = "token"];`
     */
    public var token: kotlin.String
      @kotlin.jvm.JvmName("getToken")
        get() = _builder.token
      @kotlin.jvm.JvmName("setToken")
        set(value) {
        _builder.token = value
      }
    /**
     * `string token = 2 [json_name = "token"];`
     */
    public fun clearToken() {
      _builder.clearToken()
    }
  }
}
public inline fun agent.v1.CreateTenantResponse.copy(block: `agent.v1`.CreateTenantResponseKt.Dsl.() -> kotlin.Unit): agent.v1.CreateTenantResponse =
  `agent.v1`.CreateTenantResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val agent.v1.CreateTenantResponseOrBuilder.tenantOrNull: agent.v1.Tenant?
  get() = if (hasTenant()) getTenant() else null

