// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package agent.v1;

@kotlin.jvm.JvmName("-initializediscoverGatewayModelsRequest")
public inline fun discoverGatewayModelsRequest(block: agent.v1.DiscoverGatewayModelsRequestKt.Dsl.() -> kotlin.Unit): agent.v1.DiscoverGatewayModelsRequest =
  agent.v1.DiscoverGatewayModelsRequestKt.Dsl._create(agent.v1.DiscoverGatewayModelsRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `agent.v1.DiscoverGatewayModelsRequest`
 */
public object DiscoverGatewayModelsRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: agent.v1.DiscoverGatewayModelsRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: agent.v1.DiscoverGatewayModelsRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): agent.v1.DiscoverGatewayModelsRequest = _builder.build()

    /**
     * `string provider_id = 1 [json_name = "providerId"];`
     */
    public var providerId: kotlin.String
      @kotlin.jvm.JvmName("getProviderId")
        get() = _builder.providerId
      @kotlin.jvm.JvmName("setProviderId")
        set(value) {
        _builder.providerId = value
      }
    /**
     * `string provider_id = 1 [json_name = "providerId"];`
     */
    public fun clearProviderId() {
      _builder.clearProviderId()
    }

    /**
     * `string api_type = 2 [json_name = "apiType"];`
     */
    public var apiType: kotlin.String
      @kotlin.jvm.JvmName("getApiType")
        get() = _builder.apiType
      @kotlin.jvm.JvmName("setApiType")
        set(value) {
        _builder.apiType = value
      }
    /**
     * `string api_type = 2 [json_name = "apiType"];`
     */
    public fun clearApiType() {
      _builder.clearApiType()
    }

    /**
     * `string base_url = 3 [json_name = "baseUrl"];`
     */
    public var baseUrl: kotlin.String
      @kotlin.jvm.JvmName("getBaseUrl")
        get() = _builder.baseUrl
      @kotlin.jvm.JvmName("setBaseUrl")
        set(value) {
        _builder.baseUrl = value
      }
    /**
     * `string base_url = 3 [json_name = "baseUrl"];`
     */
    public fun clearBaseUrl() {
      _builder.clearBaseUrl()
    }

    /**
     * `string api_key = 4 [json_name = "apiKey"];`
     */
    public var apiKey: kotlin.String
      @kotlin.jvm.JvmName("getApiKey")
        get() = _builder.apiKey
      @kotlin.jvm.JvmName("setApiKey")
        set(value) {
        _builder.apiKey = value
      }
    /**
     * `string api_key = 4 [json_name = "apiKey"];`
     */
    public fun clearApiKey() {
      _builder.clearApiKey()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class HeadersProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .agent.v1.DiscoverGatewayModelsRequest.HeadersEntry headers = 5 [json_name = "headers"];`
     */
     public val headers: com.google.protobuf.kotlin.DslList<agent.v1.DiscoverGatewayModelsRequest.HeadersEntry, HeadersProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.headersList
      )
    /**
     * `repeated .agent.v1.DiscoverGatewayModelsRequest.HeadersEntry headers = 5 [json_name = "headers"];`
     * @param value The headers to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addHeaders")
    public fun com.google.protobuf.kotlin.DslList<agent.v1.DiscoverGatewayModelsRequest.HeadersEntry, HeadersProxy>.add(value: agent.v1.DiscoverGatewayModelsRequest.HeadersEntry) {
      _builder.addHeaders(value)
    }
    /**
     * `repeated .agent.v1.DiscoverGatewayModelsRequest.HeadersEntry headers = 5 [json_name = "headers"];`
     * @param value The headers to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignHeaders")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<agent.v1.DiscoverGatewayModelsRequest.HeadersEntry, HeadersProxy>.plusAssign(value: agent.v1.DiscoverGatewayModelsRequest.HeadersEntry) {
      add(value)
    }
    /**
     * `repeated .agent.v1.DiscoverGatewayModelsRequest.HeadersEntry headers = 5 [json_name = "headers"];`
     * @param values The headers to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllHeaders")
    public fun com.google.protobuf.kotlin.DslList<agent.v1.DiscoverGatewayModelsRequest.HeadersEntry, HeadersProxy>.addAll(values: kotlin.collections.Iterable<agent.v1.DiscoverGatewayModelsRequest.HeadersEntry>) {
      _builder.addAllHeaders(values)
    }
    /**
     * `repeated .agent.v1.DiscoverGatewayModelsRequest.HeadersEntry headers = 5 [json_name = "headers"];`
     * @param values The headers to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllHeaders")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<agent.v1.DiscoverGatewayModelsRequest.HeadersEntry, HeadersProxy>.plusAssign(values: kotlin.collections.Iterable<agent.v1.DiscoverGatewayModelsRequest.HeadersEntry>) {
      addAll(values)
    }
    /**
     * `repeated .agent.v1.DiscoverGatewayModelsRequest.HeadersEntry headers = 5 [json_name = "headers"];`
     * @param index The index to set the value at.
     * @param value The headers to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setHeaders")
    public operator fun com.google.protobuf.kotlin.DslList<agent.v1.DiscoverGatewayModelsRequest.HeadersEntry, HeadersProxy>.set(index: kotlin.Int, value: agent.v1.DiscoverGatewayModelsRequest.HeadersEntry) {
      _builder.setHeaders(index, value)
    }
    /**
     * `repeated .agent.v1.DiscoverGatewayModelsRequest.HeadersEntry headers = 5 [json_name = "headers"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearHeaders")
    public fun com.google.protobuf.kotlin.DslList<agent.v1.DiscoverGatewayModelsRequest.HeadersEntry, HeadersProxy>.clear() {
      _builder.clearHeaders()
    }
  }
  @kotlin.jvm.JvmName("-initializeheadersEntry")
  public inline fun headersEntry(block: agent.v1.DiscoverGatewayModelsRequestKt.HeadersEntryKt.Dsl.() -> kotlin.Unit): agent.v1.DiscoverGatewayModelsRequest.HeadersEntry =
    agent.v1.DiscoverGatewayModelsRequestKt.HeadersEntryKt.Dsl._create(agent.v1.DiscoverGatewayModelsRequest.HeadersEntry.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `agent.v1.DiscoverGatewayModelsRequest.HeadersEntry`
   */
  public object HeadersEntryKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: agent.v1.DiscoverGatewayModelsRequest.HeadersEntry.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: agent.v1.DiscoverGatewayModelsRequest.HeadersEntry.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): agent.v1.DiscoverGatewayModelsRequest.HeadersEntry = _builder.build()

      /**
       * `string key = 1 [json_name = "key"];`
       */
      public var key: kotlin.String
        @kotlin.jvm.JvmName("getKey")
          get() = _builder.key
        @kotlin.jvm.JvmName("setKey")
          set(value) {
          _builder.key = value
        }
      /**
       * `string key = 1 [json_name = "key"];`
       */
      public fun clearKey() {
        _builder.clearKey()
      }

      /**
       * `string value = 2 [json_name = "value"];`
       */
      public var value: kotlin.String
        @kotlin.jvm.JvmName("getValue")
          get() = _builder.value
        @kotlin.jvm.JvmName("setValue")
          set(value) {
          _builder.value = value
        }
      /**
       * `string value = 2 [json_name = "value"];`
       */
      public fun clearValue() {
        _builder.clearValue()
      }
    }
  }
}
public inline fun agent.v1.DiscoverGatewayModelsRequest.copy(block: `agent.v1`.DiscoverGatewayModelsRequestKt.Dsl.() -> kotlin.Unit): agent.v1.DiscoverGatewayModelsRequest =
  `agent.v1`.DiscoverGatewayModelsRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public inline fun agent.v1.DiscoverGatewayModelsRequest.HeadersEntry.copy(block: `agent.v1`.DiscoverGatewayModelsRequestKt.HeadersEntryKt.Dsl.() -> kotlin.Unit): agent.v1.DiscoverGatewayModelsRequest.HeadersEntry =
  `agent.v1`.DiscoverGatewayModelsRequestKt.HeadersEntryKt.Dsl._create(this.toBuilder()).apply { block() }._build()

