// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto
// Protobuf Java Version: 4.36.1

package agent.v1;

/**
 * Protobuf type {@code agent.v1.DiscoverGatewayModelsRequest}
 */
@com.google.protobuf.Generated
public  final class DiscoverGatewayModelsRequest extends
    com.google.protobuf.GeneratedMessageLite<
        DiscoverGatewayModelsRequest, DiscoverGatewayModelsRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:agent.v1.DiscoverGatewayModelsRequest)
    DiscoverGatewayModelsRequestOrBuilder {
  private DiscoverGatewayModelsRequest() {
    providerId_ = "";
    apiType_ = "";
    baseUrl_ = "";
    apiKey_ = "";
    headers_ = emptyProtobufList();
  }
  public interface HeadersEntryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:agent.v1.DiscoverGatewayModelsRequest.HeadersEntry)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string key = 1 [json_name = "key"];</code>
     * @return The key.
     */
    java.lang.String getKey();
    /**
     * <code>string key = 1 [json_name = "key"];</code>
     * @return The bytes for key.
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>string value = 2 [json_name = "value"];</code>
     * @return The value.
     */
    java.lang.String getValue();
    /**
     * <code>string value = 2 [json_name = "value"];</code>
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code agent.v1.DiscoverGatewayModelsRequest.HeadersEntry}
   */
  public  static final class HeadersEntry extends
      com.google.protobuf.GeneratedMessageLite<
          HeadersEntry, HeadersEntry.Builder> implements
      // @@protoc_insertion_point(message_implements:agent.v1.DiscoverGatewayModelsRequest.HeadersEntry)
      HeadersEntryOrBuilder {
    private HeadersEntry() {
      key_ = "";
      value_ = "";
    }
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.String key_;
    /**
     * <code>string key = 1 [json_name = "key"];</code>
     * @return The key.
     */
    @java.lang.Override
    public java.lang.String getKey() {
      return key_;
    }
    /**
     * <code>string key = 1 [json_name = "key"];</code>
     * @return The bytes for key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeyBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(key_);
    }
    /**
     * <code>string key = 1 [json_name = "key"];</code>
     * @param value The key to set.
     */
    private void setKey(
        java.lang.String value) {
      java.util.Objects.requireNonNull(value);

      key_ = value;
    }
    /**
     * <code>string key = 1 [json_name = "key"];</code>
     */
    private void clearKey() {

      key_ = getDefaultInstance().getKey();
    }
    /**
     * <code>string key = 1 [json_name = "key"];</code>
     * @param value The bytes for key to set.
     */
    private void setKeyBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      key_ = value.toStringUtf8();

    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private java.lang.String value_;
    /**
     * <code>string value = 2 [json_name = "value"];</code>
     * @return The value.
     */
    @java.lang.Override
    public java.lang.String getValue() {
      return value_;
    }
    /**
     * <code>string value = 2 [json_name = "value"];</code>
     * @return The bytes for value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValueBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(value_);
    }
    /**
     * <code>string value = 2 [json_name = "value"];</code>
     * @param value The value to set.
     */
    private void setValue(
        java.lang.String value) {
      java.util.Objects.requireNonNull(value);

      value_ = value;
    }
    /**
     * <code>string value = 2 [json_name = "value"];</code>
     */
    private void clearValue() {

      value_ = getDefaultInstance().getValue();
    }
    /**
     * <code>string value = 2 [json_name = "value"];</code>
     * @param value The bytes for value to set.
     */
    private void setValueBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      value_ = value.toStringUtf8();

    }

    public static agent.v1.DiscoverGatewayModelsRequest.HeadersEntry parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static agent.v1.DiscoverGatewayModelsRequest.HeadersEntry parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static agent.v1.DiscoverGatewayModelsRequest.HeadersEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static agent.v1.DiscoverGatewayModelsRequest.HeadersEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static agent.v1.DiscoverGatewayModelsRequest.HeadersEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static agent.v1.DiscoverGatewayModelsRequest.HeadersEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static agent.v1.DiscoverGatewayModelsRequest.HeadersEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static agent.v1.DiscoverGatewayModelsRequest.HeadersEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static agent.v1.DiscoverGatewayModelsRequest.HeadersEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static agent.v1.DiscoverGatewayModelsRequest.HeadersEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static agent.v1.DiscoverGatewayModelsRequest.HeadersEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static agent.v1.DiscoverGatewayModelsRequest.HeadersEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(agent.v1.DiscoverGatewayModelsRequest.HeadersEntry prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code agent.v1.DiscoverGatewayModelsRequest.HeadersEntry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          agent.v1.DiscoverGatewayModelsRequest.HeadersEntry, Builder> implements
        // @@protoc_insertion_point(builder_implements:agent.v1.DiscoverGatewayModelsRequest.HeadersEntry)
        agent.v1.DiscoverGatewayModelsRequest.HeadersEntryOrBuilder {
      // Construct using agent.v1.DiscoverGatewayModelsRequest.HeadersEntry.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string key = 1 [json_name = "key"];</code>
       * @return The key.
       */
      @java.lang.Override
      public java.lang.String getKey() {
        return instance.getKey();
      }
      /**
       * <code>string key = 1 [json_name = "key"];</code>
       * @return The bytes for key.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getKeyBytes() {
        return instance.getKeyBytes();
      }
      /**
       * <code>string key = 1 [json_name = "key"];</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(
          java.lang.String value) {
        copyOnWrite();
        instance.setKey(value);
        return this;
      }
      /**
       * <code>string key = 1 [json_name = "key"];</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        copyOnWrite();
        instance.clearKey();
        return this;
      }
      /**
       * <code>string key = 1 [json_name = "key"];</code>
       * @param value The bytes for key to set.
       * @return This builder for chaining.
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setKeyBytes(value);
        return this;
      }

      /**
       * <code>string value = 2 [json_name = "value"];</code>
       * @return The value.
       */
      @java.lang.Override
      public java.lang.String getValue() {
        return instance.getValue();
      }
      /**
       * <code>string value = 2 [json_name = "value"];</code>
       * @return The bytes for value.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getValueBytes() {
        return instance.getValueBytes();
      }
      /**
       * <code>string value = 2 [json_name = "value"];</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(
          java.lang.String value) {
        copyOnWrite();
        instance.setValue(value);
        return this;
      }
      /**
       * <code>string value = 2 [json_name = "value"];</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        copyOnWrite();
        instance.clearValue();
        return this;
      }
      /**
       * <code>string value = 2 [json_name = "value"];</code>
       * @param value The bytes for value to set.
       * @return This builder for chaining.
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setValueBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:agent.v1.DiscoverGatewayModelsRequest.HeadersEntry)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new agent.v1.DiscoverGatewayModelsRequest.HeadersEntry();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "key_",
              "value_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<agent.v1.DiscoverGatewayModelsRequest.HeadersEntry> parser = PARSER;
          if (parser == null) {
            synchronized (agent.v1.DiscoverGatewayModelsRequest.HeadersEntry.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<agent.v1.DiscoverGatewayModelsRequest.HeadersEntry>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:agent.v1.DiscoverGatewayModelsRequest.HeadersEntry)
    private static final agent.v1.DiscoverGatewayModelsRequest.HeadersEntry DEFAULT_INSTANCE;
    static {
      HeadersEntry defaultInstance = new HeadersEntry();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        HeadersEntry.class, defaultInstance);
    }

    public static agent.v1.DiscoverGatewayModelsRequest.HeadersEntry getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<HeadersEntry> PARSER;

    public static com.google.protobuf.Parser<HeadersEntry> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public static final int PROVIDER_ID_FIELD_NUMBER = 1;
  private java.lang.String providerId_;
  /**
   * <code>string provider_id = 1 [json_name = "providerId"];</code>
   * @return The providerId.
   */
  @java.lang.Override
  public java.lang.String getProviderId() {
    return providerId_;
  }
  /**
   * <code>string provider_id = 1 [json_name = "providerId"];</code>
   * @return The bytes for providerId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProviderIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(providerId_);
  }
  /**
   * <code>string provider_id = 1 [json_name = "providerId"];</code>
   * @param value The providerId to set.
   */
  private void setProviderId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    providerId_ = value;
  }
  /**
   * <code>string provider_id = 1 [json_name = "providerId"];</code>
   */
  private void clearProviderId() {

    providerId_ = getDefaultInstance().getProviderId();
  }
  /**
   * <code>string provider_id = 1 [json_name = "providerId"];</code>
   * @param value The bytes for providerId to set.
   */
  private void setProviderIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    providerId_ = value.toStringUtf8();

  }

  public static final int API_TYPE_FIELD_NUMBER = 2;
  private java.lang.String apiType_;
  /**
   * <code>string api_type = 2 [json_name = "apiType"];</code>
   * @return The apiType.
   */
  @java.lang.Override
  public java.lang.String getApiType() {
    return apiType_;
  }
  /**
   * <code>string api_type = 2 [json_name = "apiType"];</code>
   * @return The bytes for apiType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getApiTypeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(apiType_);
  }
  /**
   * <code>string api_type = 2 [json_name = "apiType"];</code>
   * @param value The apiType to set.
   */
  private void setApiType(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    apiType_ = value;
  }
  /**
   * <code>string api_type = 2 [json_name = "apiType"];</code>
   */
  private void clearApiType() {

    apiType_ = getDefaultInstance().getApiType();
  }
  /**
   * <code>string api_type = 2 [json_name = "apiType"];</code>
   * @param value The bytes for apiType to set.
   */
  private void setApiTypeBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    apiType_ = value.toStringUtf8();

  }

  public static final int BASE_URL_FIELD_NUMBER = 3;
  private java.lang.String baseUrl_;
  /**
   * <code>string base_url = 3 [json_name = "baseUrl"];</code>
   * @return The baseUrl.
   */
  @java.lang.Override
  public java.lang.String getBaseUrl() {
    return baseUrl_;
  }
  /**
   * <code>string base_url = 3 [json_name = "baseUrl"];</code>
   * @return The bytes for baseUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBaseUrlBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(baseUrl_);
  }
  /**
   * <code>string base_url = 3 [json_name = "baseUrl"];</code>
   * @param value The baseUrl to set.
   */
  private void setBaseUrl(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    baseUrl_ = value;
  }
  /**
   * <code>string base_url = 3 [json_name = "baseUrl"];</code>
   */
  private void clearBaseUrl() {

    baseUrl_ = getDefaultInstance().getBaseUrl();
  }
  /**
   * <code>string base_url = 3 [json_name = "baseUrl"];</code>
   * @param value The bytes for baseUrl to set.
   */
  private void setBaseUrlBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    baseUrl_ = value.toStringUtf8();

  }

  public static final int API_KEY_FIELD_NUMBER = 4;
  private java.lang.String apiKey_;
  /**
   * <code>string api_key = 4 [json_name = "apiKey"];</code>
   * @return The apiKey.
   */
  @java.lang.Override
  public java.lang.String getApiKey() {
    return apiKey_;
  }
  /**
   * <code>string api_key = 4 [json_name = "apiKey"];</code>
   * @return The bytes for apiKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getApiKeyBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(apiKey_);
  }
  /**
   * <code>string api_key = 4 [json_name = "apiKey"];</code>
   * @param value The apiKey to set.
   */
  private void setApiKey(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    apiKey_ = value;
  }
  /**
   * <code>string api_key = 4 [json_name = "apiKey"];</code>
   */
  private void clearApiKey() {

    apiKey_ = getDefaultInstance().getApiKey();
  }
  /**
   * <code>string api_key = 4 [json_name = "apiKey"];</code>
   * @param value The bytes for apiKey to set.
   */
  private void setApiKeyBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    apiKey_ = value.toStringUtf8();

  }

  public static final int HEADERS_FIELD_NUMBER = 5;
  private com.google.protobuf.Internal.ProtobufList<agent.v1.DiscoverGatewayModelsRequest.HeadersEntry> headers_;
  /**
   * <code>repeated .agent.v1.DiscoverGatewayModelsRequest.HeadersEntry headers = 5 [json_name = "headers"];</code>
   */
  @java.lang.Override
  public java.util.List<agent.v1.DiscoverGatewayModelsRequest.HeadersEntry> getHeadersList() {
    return headers_;
  }
  /**
   * <code>repeated .agent.v1.DiscoverGatewayModelsRequest.HeadersEntry headers = 5 [json_name = "headers"];</code>
   */
  public java.util.List<? extends agent.v1.DiscoverGatewayModelsRequest.HeadersEntryOrBuilder> 
      getHeadersOrBuilderList() {
    return headers_;
  }
  /**
   * <code>repeated .agent.v1.DiscoverGatewayModelsRequest.HeadersEntry headers = 5 [json_name = "headers"];</code>
   */
  @java.lang.Override
  public int getHeadersCount() {
    return headers_.size();
  }
  /**
   * <code>repeated .agent.v1.DiscoverGatewayModelsRequest.HeadersEntry headers = 5 [json_name = "headers"];</code>
   */
  @java.lang.Override
  public agent.v1.DiscoverGatewayModelsRequest.HeadersEntry getHeaders(int index) {
    return headers_.get(index);
  }
  /**
   * <code>repeated .agent.v1.DiscoverGatewayModelsRequest.HeadersEntry headers = 5 [json_name = "headers"];</code>
   */
  public agent.v1.DiscoverGatewayModelsRequest.HeadersEntryOrBuilder getHeadersOrBuilder(
      int index) {
    return headers_.get(index);
  }
  private void ensureHeadersIsMutable() {
    com.google.protobuf.Internal.ProtobufList<agent.v1.DiscoverGatewayModelsRequest.HeadersEntry> tmp = headers_;
    if (!tmp.isModifiable()) {
      headers_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .agent.v1.DiscoverGatewayModelsRequest.HeadersEntry headers = 5 [json_name = "headers"];</code>
   */
  private void setHeaders(
      int index, agent.v1.DiscoverGatewayModelsRequest.HeadersEntry value) {
    java.util.Objects.requireNonNull(value);
    ensureHeadersIsMutable();
    headers_.set(index, value);
  }
  /**
   * <code>repeated .agent.v1.DiscoverGatewayModelsRequest.HeadersEntry headers = 5 [json_name = "headers"];</code>
   */
  private void addHeaders(agent.v1.DiscoverGatewayModelsRequest.HeadersEntry value) {
    java.util.Objects.requireNonNull(value);
    ensureHeadersIsMutable();
    headers_.add(value);
  }
  /**
   * <code>repeated .agent.v1.DiscoverGatewayModelsRequest.HeadersEntry headers = 5 [json_name = "headers"];</code>
   */
  private void addHeaders(
      int index, agent.v1.DiscoverGatewayModelsRequest.HeadersEntry value) {
    java.util.Objects.requireNonNull(value);
    ensureHeadersIsMutable();
    headers_.add(index, value);
  }
  /**
   * <code>repeated .agent.v1.DiscoverGatewayModelsRequest.HeadersEntry headers = 5 [json_name = "headers"];</code>
   */
  private void addAllHeaders(
      java.lang.Iterable<? extends agent.v1.DiscoverGatewayModelsRequest.HeadersEntry> values) {
    ensureHeadersIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, headers_);
  }
  /**
   * <code>repeated .agent.v1.DiscoverGatewayModelsRequest.HeadersEntry headers = 5 [json_name = "headers"];</code>
   */
  private void clearHeaders() {
    headers_ = emptyProtobufList();
  }
  /**
   * <code>repeated .agent.v1.DiscoverGatewayModelsRequest.HeadersEntry headers = 5 [json_name = "headers"];</code>
   */
  private void removeHeaders(int index) {
    ensureHeadersIsMutable();
    headers_.remove(index);
  }

  public static agent.v1.DiscoverGatewayModelsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static agent.v1.DiscoverGatewayModelsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static agent.v1.DiscoverGatewayModelsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static agent.v1.DiscoverGatewayModelsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static agent.v1.DiscoverGatewayModelsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static agent.v1.DiscoverGatewayModelsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static agent.v1.DiscoverGatewayModelsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static agent.v1.DiscoverGatewayModelsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static agent.v1.DiscoverGatewayModelsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static agent.v1.DiscoverGatewayModelsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static agent.v1.DiscoverGatewayModelsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static agent.v1.DiscoverGatewayModelsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(agent.v1.DiscoverGatewayModelsRequest prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code agent.v1.DiscoverGatewayModelsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        agent.v1.DiscoverGatewayModelsRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:agent.v1.DiscoverGatewayModelsRequest)
      agent.v1.DiscoverGatewayModelsRequestOrBuilder {
    // Construct using agent.v1.DiscoverGatewayModelsRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string provider_id = 1 [json_name = "providerId"];</code>
     * @return The providerId.
     */
    @java.lang.Override
    public java.lang.String getProviderId() {
      return instance.getProviderId();
    }
    /**
     * <code>string provider_id = 1 [json_name = "providerId"];</code>
     * @return The bytes for providerId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProviderIdBytes() {
      return instance.getProviderIdBytes();
    }
    /**
     * <code>string provider_id = 1 [json_name = "providerId"];</code>
     * @param value The providerId to set.
     * @return This builder for chaining.
     */
    public Builder setProviderId(
        java.lang.String value) {
      copyOnWrite();
      instance.setProviderId(value);
      return this;
    }
    /**
     * <code>string provider_id = 1 [json_name = "providerId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearProviderId() {
      copyOnWrite();
      instance.clearProviderId();
      return this;
    }
    /**
     * <code>string provider_id = 1 [json_name = "providerId"];</code>
     * @param value The bytes for providerId to set.
     * @return This builder for chaining.
     */
    public Builder setProviderIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setProviderIdBytes(value);
      return this;
    }

    /**
     * <code>string api_type = 2 [json_name = "apiType"];</code>
     * @return The apiType.
     */
    @java.lang.Override
    public java.lang.String getApiType() {
      return instance.getApiType();
    }
    /**
     * <code>string api_type = 2 [json_name = "apiType"];</code>
     * @return The bytes for apiType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getApiTypeBytes() {
      return instance.getApiTypeBytes();
    }
    /**
     * <code>string api_type = 2 [json_name = "apiType"];</code>
     * @param value The apiType to set.
     * @return This builder for chaining.
     */
    public Builder setApiType(
        java.lang.String value) {
      copyOnWrite();
      instance.setApiType(value);
      return this;
    }
    /**
     * <code>string api_type = 2 [json_name = "apiType"];</code>
     * @return This builder for chaining.
     */
    public Builder clearApiType() {
      copyOnWrite();
      instance.clearApiType();
      return this;
    }
    /**
     * <code>string api_type = 2 [json_name = "apiType"];</code>
     * @param value The bytes for apiType to set.
     * @return This builder for chaining.
     */
    public Builder setApiTypeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setApiTypeBytes(value);
      return this;
    }

    /**
     * <code>string base_url = 3 [json_name = "baseUrl"];</code>
     * @return The baseUrl.
     */
    @java.lang.Override
    public java.lang.String getBaseUrl() {
      return instance.getBaseUrl();
    }
    /**
     * <code>string base_url = 3 [json_name = "baseUrl"];</code>
     * @return The bytes for baseUrl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBaseUrlBytes() {
      return instance.getBaseUrlBytes();
    }
    /**
     * <code>string base_url = 3 [json_name = "baseUrl"];</code>
     * @param value The baseUrl to set.
     * @return This builder for chaining.
     */
    public Builder setBaseUrl(
        java.lang.String value) {
      copyOnWrite();
      instance.setBaseUrl(value);
      return this;
    }
    /**
     * <code>string base_url = 3 [json_name = "baseUrl"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBaseUrl() {
      copyOnWrite();
      instance.clearBaseUrl();
      return this;
    }
    /**
     * <code>string base_url = 3 [json_name = "baseUrl"];</code>
     * @param value The bytes for baseUrl to set.
     * @return This builder for chaining.
     */
    public Builder setBaseUrlBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setBaseUrlBytes(value);
      return this;
    }

    /**
     * <code>string api_key = 4 [json_name = "apiKey"];</code>
     * @return The apiKey.
     */
    @java.lang.Override
    public java.lang.String getApiKey() {
      return instance.getApiKey();
    }
    /**
     * <code>string api_key = 4 [json_name = "apiKey"];</code>
     * @return The bytes for apiKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getApiKeyBytes() {
      return instance.getApiKeyBytes();
    }
    /**
     * <code>string api_key = 4 [json_name = "apiKey"];</code>
     * @param value The apiKey to set.
     * @return This builder for chaining.
     */
    public Builder setApiKey(
        java.lang.String value) {
      copyOnWrite();
      instance.setApiKey(value);
      return this;
    }
    /**
     * <code>string api_key = 4 [json_name = "apiKey"];</code>
     * @return This builder for chaining.
     */
    public Builder clearApiKey() {
      copyOnWrite();
      instance.clearApiKey();
      return this;
    }
    /**
     * <code>string api_key = 4 [json_name = "apiKey"];</code>
     * @param value The bytes for apiKey to set.
     * @return This builder for chaining.
     */
    public Builder setApiKeyBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setApiKeyBytes(value);
      return this;
    }

    /**
     * <code>repeated .agent.v1.DiscoverGatewayModelsRequest.HeadersEntry headers = 5 [json_name = "headers"];</code>
     */
    @java.lang.Override
    public java.util.List<agent.v1.DiscoverGatewayModelsRequest.HeadersEntry> getHeadersList() {
      return java.util.Collections.unmodifiableList(
          instance.getHeadersList());
    }
    /**
     * <code>repeated .agent.v1.DiscoverGatewayModelsRequest.HeadersEntry headers = 5 [json_name = "headers"];</code>
     */
    @java.lang.Override
    public int getHeadersCount() {
      return instance.getHeadersCount();
    }/**
     * <code>repeated .agent.v1.DiscoverGatewayModelsRequest.HeadersEntry headers = 5 [json_name = "headers"];</code>
     */
    @java.lang.Override
    public agent.v1.DiscoverGatewayModelsRequest.HeadersEntry getHeaders(int index) {
      return instance.getHeaders(index);
    }
    /**
     * <code>repeated .agent.v1.DiscoverGatewayModelsRequest.HeadersEntry headers = 5 [json_name = "headers"];</code>
     */
    public Builder setHeaders(
        int index, agent.v1.DiscoverGatewayModelsRequest.HeadersEntry value) {
      copyOnWrite();
      instance.setHeaders(index, value);
      return this;
    }
    /**
     * <code>repeated .agent.v1.DiscoverGatewayModelsRequest.HeadersEntry headers = 5 [json_name = "headers"];</code>
     */
    public Builder setHeaders(
        int index, agent.v1.DiscoverGatewayModelsRequest.HeadersEntry.Builder builderForValue) {
      copyOnWrite();
      instance.setHeaders(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .agent.v1.DiscoverGatewayModelsRequest.HeadersEntry headers = 5 [json_name = "headers"];</code>
     */
    public Builder addHeaders(agent.v1.DiscoverGatewayModelsRequest.HeadersEntry value) {
      copyOnWrite();
      instance.addHeaders(value);
      return this;
    }
    /**
     * <code>repeated .agent.v1.DiscoverGatewayModelsRequest.HeadersEntry headers = 5 [json_name = "headers"];</code>
     */
    public Builder addHeaders(
        int index, agent.v1.DiscoverGatewayModelsRequest.HeadersEntry value) {
      copyOnWrite();
      instance.addHeaders(index, value);
      return this;
    }
    /**
     * <code>repeated .agent.v1.DiscoverGatewayModelsRequest.HeadersEntry headers = 5 [json_name = "headers"];</code>
     */
    public Builder addHeaders(
        agent.v1.DiscoverGatewayModelsRequest.HeadersEntry.Builder builderForValue) {
      copyOnWrite();
      instance.addHeaders(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .agent.v1.DiscoverGatewayModelsRequest.HeadersEntry headers = 5 [json_name = "headers"];</code>
     */
    public Builder addHeaders(
        int index, agent.v1.DiscoverGatewayModelsRequest.HeadersEntry.Builder builderForValue) {
      copyOnWrite();
      instance.addHeaders(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .agent.v1.DiscoverGatewayModelsRequest.HeadersEntry headers = 5 [json_name = "headers"];</code>
     */
    public Builder addAllHeaders(
        java.lang.Iterable<? extends agent.v1.DiscoverGatewayModelsRequest.HeadersEntry> values) {
      copyOnWrite();
      instance.addAllHeaders(values);
      return this;
    }
    /**
     * <code>repeated .agent.v1.DiscoverGatewayModelsRequest.HeadersEntry headers = 5 [json_name = "headers"];</code>
     */
    public Builder clearHeaders() {
      copyOnWrite();
      instance.clearHeaders();
      return this;
    }
    /**
     * <code>repeated .agent.v1.DiscoverGatewayModelsRequest.HeadersEntry headers = 5 [json_name = "headers"];</code>
     */
    public Builder removeHeaders(int index) {
      copyOnWrite();
      instance.removeHeaders(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:agent.v1.DiscoverGatewayModelsRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new agent.v1.DiscoverGatewayModelsRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "providerId_",
            "apiType_",
            "baseUrl_",
            "apiKey_",
            "headers_",
            agent.v1.DiscoverGatewayModelsRequest.HeadersEntry.class,
          };
          java.lang.String info =
              "\u0000\u0005\u0000\u0000\u0001\u0005\u0005\u0000\u0001\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208\u0004\u0208\u0005\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<agent.v1.DiscoverGatewayModelsRequest> parser = PARSER;
        if (parser == null) {
          synchronized (agent.v1.DiscoverGatewayModelsRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<agent.v1.DiscoverGatewayModelsRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:agent.v1.DiscoverGatewayModelsRequest)
  private static final agent.v1.DiscoverGatewayModelsRequest DEFAULT_INSTANCE;
  static {
    DiscoverGatewayModelsRequest defaultInstance = new DiscoverGatewayModelsRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      DiscoverGatewayModelsRequest.class, defaultInstance);
  }

  public static agent.v1.DiscoverGatewayModelsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<DiscoverGatewayModelsRequest> PARSER;

  public static com.google.protobuf.Parser<DiscoverGatewayModelsRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

