// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package agent.v1;

@kotlin.jvm.JvmName("-initializeforkResponse")
public inline fun forkResponse(block: agent.v1.ForkResponseKt.Dsl.() -> kotlin.Unit): agent.v1.ForkResponse =
  agent.v1.ForkResponseKt.Dsl._create(agent.v1.ForkResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `agent.v1.ForkResponse`
 */
public object ForkResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: agent.v1.ForkResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: agent.v1.ForkResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): agent.v1.ForkResponse = _builder.build()

    /**
     * `.agent.v1.Session session = 1 [json_name = "session"];`
     */
    public var session: agent.v1.Session
      @kotlin.jvm.JvmName("getSession")
        get() = _builder.session
      @kotlin.jvm.JvmName("setSession")
        set(value) {
        _builder.session = value
      }
    /**
     * `.agent.v1.Session session = 1 [json_name = "session"];`
     */
    public fun clearSession() {
      _builder.clearSession()
    }
    /**
     * `.agent.v1.Session session = 1 [json_name = "session"];`
     * @return Whether the session field is set.
     */
    public fun hasSession(): kotlin.Boolean {
      return _builder.hasSession()
    }

    public val ForkResponseKt.Dsl.sessionOrNull: agent.v1.Session?
      get() = _builder.sessionOrNull
  }
}
public inline fun agent.v1.ForkResponse.copy(block: `agent.v1`.ForkResponseKt.Dsl.() -> kotlin.Unit): agent.v1.ForkResponse =
  `agent.v1`.ForkResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val agent.v1.ForkResponseOrBuilder.sessionOrNull: agent.v1.Session?
  get() = if (hasSession()) getSession() else null

