// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package agent.v1;

@kotlin.jvm.JvmName("-initializegetFileRequest")
public inline fun getFileRequest(block: agent.v1.GetFileRequestKt.Dsl.() -> kotlin.Unit): agent.v1.GetFileRequest =
  agent.v1.GetFileRequestKt.Dsl._create(agent.v1.GetFileRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `agent.v1.GetFileRequest`
 */
public object GetFileRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: agent.v1.GetFileRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: agent.v1.GetFileRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): agent.v1.GetFileRequest = _builder.build()

    /**
     * `string code = 1 [json_name = "code"];`
     */
    public var code: kotlin.String
      @kotlin.jvm.JvmName("getCode")
        get() = _builder.code
      @kotlin.jvm.JvmName("setCode")
        set(value) {
        _builder.code = value
      }
    /**
     * `string code = 1 [json_name = "code"];`
     */
    public fun clearCode() {
      _builder.clearCode()
    }
  }
}
public inline fun agent.v1.GetFileRequest.copy(block: `agent.v1`.GetFileRequestKt.Dsl.() -> kotlin.Unit): agent.v1.GetFileRequest =
  `agent.v1`.GetFileRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

