// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package agent.v1;

@kotlin.jvm.JvmName("-initializeissueTenantTokenRequest")
public inline fun issueTenantTokenRequest(block: agent.v1.IssueTenantTokenRequestKt.Dsl.() -> kotlin.Unit): agent.v1.IssueTenantTokenRequest =
  agent.v1.IssueTenantTokenRequestKt.Dsl._create(agent.v1.IssueTenantTokenRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `agent.v1.IssueTenantTokenRequest`
 */
public object IssueTenantTokenRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: agent.v1.IssueTenantTokenRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: agent.v1.IssueTenantTokenRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): agent.v1.IssueTenantTokenRequest = _builder.build()

    /**
     * `string tenant_id = 1 [json_name = "tenantId"];`
     */
    public var tenantId: kotlin.String
      @kotlin.jvm.JvmName("getTenantId")
        get() = _builder.tenantId
      @kotlin.jvm.JvmName("setTenantId")
        set(value) {
        _builder.tenantId = value
      }
    /**
     * `string tenant_id = 1 [json_name = "tenantId"];`
     */
    public fun clearTenantId() {
      _builder.clearTenantId()
    }

    /**
     * `string label = 2 [json_name = "label"];`
     */
    public var label: kotlin.String
      @kotlin.jvm.JvmName("getLabel")
        get() = _builder.label
      @kotlin.jvm.JvmName("setLabel")
        set(value) {
        _builder.label = value
      }
    /**
     * `string label = 2 [json_name = "label"];`
     */
    public fun clearLabel() {
      _builder.clearLabel()
    }
  }
}
public inline fun agent.v1.IssueTenantTokenRequest.copy(block: `agent.v1`.IssueTenantTokenRequestKt.Dsl.() -> kotlin.Unit): agent.v1.IssueTenantTokenRequest =
  `agent.v1`.IssueTenantTokenRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

