// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package agent.v1;

@kotlin.jvm.JvmName("-initializeissueTenantTokenResponse")
public inline fun issueTenantTokenResponse(block: agent.v1.IssueTenantTokenResponseKt.Dsl.() -> kotlin.Unit): agent.v1.IssueTenantTokenResponse =
  agent.v1.IssueTenantTokenResponseKt.Dsl._create(agent.v1.IssueTenantTokenResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `agent.v1.IssueTenantTokenResponse`
 */
public object IssueTenantTokenResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: agent.v1.IssueTenantTokenResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: agent.v1.IssueTenantTokenResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): agent.v1.IssueTenantTokenResponse = _builder.build()

    /**
     * `.agent.v1.TenantToken token = 1 [json_name = "token"];`
     */
    public var token: agent.v1.TenantToken
      @kotlin.jvm.JvmName("getToken")
        get() = _builder.token
      @kotlin.jvm.JvmName("setToken")
        set(value) {
        _builder.token = value
      }
    /**
     * `.agent.v1.TenantToken token = 1 [json_name = "token"];`
     */
    public fun clearToken() {
      _builder.clearToken()
    }
    /**
     * `.agent.v1.TenantToken token = 1 [json_name = "token"];`
     * @return Whether the token field is set.
     */
    public fun hasToken(): kotlin.Boolean {
      return _builder.hasToken()
    }

    public val IssueTenantTokenResponseKt.Dsl.tokenOrNull: agent.v1.TenantToken?
      get() = _builder.tokenOrNull

    /**
     * `string plaintext = 2 [json_name = "plaintext"];`
     */
    public var plaintext: kotlin.String
      @kotlin.jvm.JvmName("getPlaintext")
        get() = _builder.plaintext
      @kotlin.jvm.JvmName("setPlaintext")
        set(value) {
        _builder.plaintext = value
      }
    /**
     * `string plaintext = 2 [json_name = "plaintext"];`
     */
    public fun clearPlaintext() {
      _builder.clearPlaintext()
    }
  }
}
public inline fun agent.v1.IssueTenantTokenResponse.copy(block: `agent.v1`.IssueTenantTokenResponseKt.Dsl.() -> kotlin.Unit): agent.v1.IssueTenantTokenResponse =
  `agent.v1`.IssueTenantTokenResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val agent.v1.IssueTenantTokenResponseOrBuilder.tokenOrNull: agent.v1.TenantToken?
  get() = if (hasToken()) getToken() else null

