// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package agent.v1;

@kotlin.jvm.JvmName("-initializelistTenantTokensRequest")
public inline fun listTenantTokensRequest(block: agent.v1.ListTenantTokensRequestKt.Dsl.() -> kotlin.Unit): agent.v1.ListTenantTokensRequest =
  agent.v1.ListTenantTokensRequestKt.Dsl._create(agent.v1.ListTenantTokensRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `agent.v1.ListTenantTokensRequest`
 */
public object ListTenantTokensRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: agent.v1.ListTenantTokensRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: agent.v1.ListTenantTokensRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): agent.v1.ListTenantTokensRequest = _builder.build()

    /**
     * `string tenant_id = 1 [json_name = "tenantId"];`
     */
    public var tenantId: kotlin.String
      @kotlin.jvm.JvmName("getTenantId")
        get() = _builder.tenantId
      @kotlin.jvm.JvmName("setTenantId")
        set(value) {
        _builder.tenantId = value
      }
    /**
     * `string tenant_id = 1 [json_name = "tenantId"];`
     */
    public fun clearTenantId() {
      _builder.clearTenantId()
    }
  }
}
public inline fun agent.v1.ListTenantTokensRequest.copy(block: `agent.v1`.ListTenantTokensRequestKt.Dsl.() -> kotlin.Unit): agent.v1.ListTenantTokensRequest =
  `agent.v1`.ListTenantTokensRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

