// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package agent.v1;

@kotlin.jvm.JvmName("-initializelistModelsRequest")
public inline fun listModelsRequest(block: agent.v1.ListModelsRequestKt.Dsl.() -> kotlin.Unit): agent.v1.ListModelsRequest =
  agent.v1.ListModelsRequestKt.Dsl._create(agent.v1.ListModelsRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `agent.v1.ListModelsRequest`
 */
public object ListModelsRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: agent.v1.ListModelsRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: agent.v1.ListModelsRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): agent.v1.ListModelsRequest = _builder.build()

    /**
     * `string provider_id = 1 [json_name = "providerId"];`
     */
    public var providerId: kotlin.String
      @kotlin.jvm.JvmName("getProviderId")
        get() = _builder.providerId
      @kotlin.jvm.JvmName("setProviderId")
        set(value) {
        _builder.providerId = value
      }
    /**
     * `string provider_id = 1 [json_name = "providerId"];`
     */
    public fun clearProviderId() {
      _builder.clearProviderId()
    }
  }
}
public inline fun agent.v1.ListModelsRequest.copy(block: `agent.v1`.ListModelsRequestKt.Dsl.() -> kotlin.Unit): agent.v1.ListModelsRequest =
  `agent.v1`.ListModelsRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

