// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package agent.v1;

@kotlin.jvm.JvmName("-initializelistProvidersCatalogResponse")
public inline fun listProvidersCatalogResponse(block: agent.v1.ListProvidersCatalogResponseKt.Dsl.() -> kotlin.Unit): agent.v1.ListProvidersCatalogResponse =
  agent.v1.ListProvidersCatalogResponseKt.Dsl._create(agent.v1.ListProvidersCatalogResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `agent.v1.ListProvidersCatalogResponse`
 */
public object ListProvidersCatalogResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: agent.v1.ListProvidersCatalogResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: agent.v1.ListProvidersCatalogResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): agent.v1.ListProvidersCatalogResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ProvidersProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .agent.v1.ListProvidersCatalogResponse.ProvidersEntry providers = 1 [json_name = "providers"];`
     */
     public val providers: com.google.protobuf.kotlin.DslList<agent.v1.ListProvidersCatalogResponse.ProvidersEntry, ProvidersProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.providersList
      )
    /**
     * `repeated .agent.v1.ListProvidersCatalogResponse.ProvidersEntry providers = 1 [json_name = "providers"];`
     * @param value The providers to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addProviders")
    public fun com.google.protobuf.kotlin.DslList<agent.v1.ListProvidersCatalogResponse.ProvidersEntry, ProvidersProxy>.add(value: agent.v1.ListProvidersCatalogResponse.ProvidersEntry) {
      _builder.addProviders(value)
    }
    /**
     * `repeated .agent.v1.ListProvidersCatalogResponse.ProvidersEntry providers = 1 [json_name = "providers"];`
     * @param value The providers to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignProviders")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<agent.v1.ListProvidersCatalogResponse.ProvidersEntry, ProvidersProxy>.plusAssign(value: agent.v1.ListProvidersCatalogResponse.ProvidersEntry) {
      add(value)
    }
    /**
     * `repeated .agent.v1.ListProvidersCatalogResponse.ProvidersEntry providers = 1 [json_name = "providers"];`
     * @param values The providers to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllProviders")
    public fun com.google.protobuf.kotlin.DslList<agent.v1.ListProvidersCatalogResponse.ProvidersEntry, ProvidersProxy>.addAll(values: kotlin.collections.Iterable<agent.v1.ListProvidersCatalogResponse.ProvidersEntry>) {
      _builder.addAllProviders(values)
    }
    /**
     * `repeated .agent.v1.ListProvidersCatalogResponse.ProvidersEntry providers = 1 [json_name = "providers"];`
     * @param values The providers to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllProviders")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<agent.v1.ListProvidersCatalogResponse.ProvidersEntry, ProvidersProxy>.plusAssign(values: kotlin.collections.Iterable<agent.v1.ListProvidersCatalogResponse.ProvidersEntry>) {
      addAll(values)
    }
    /**
     * `repeated .agent.v1.ListProvidersCatalogResponse.ProvidersEntry providers = 1 [json_name = "providers"];`
     * @param index The index to set the value at.
     * @param value The providers to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setProviders")
    public operator fun com.google.protobuf.kotlin.DslList<agent.v1.ListProvidersCatalogResponse.ProvidersEntry, ProvidersProxy>.set(index: kotlin.Int, value: agent.v1.ListProvidersCatalogResponse.ProvidersEntry) {
      _builder.setProviders(index, value)
    }
    /**
     * `repeated .agent.v1.ListProvidersCatalogResponse.ProvidersEntry providers = 1 [json_name = "providers"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearProviders")
    public fun com.google.protobuf.kotlin.DslList<agent.v1.ListProvidersCatalogResponse.ProvidersEntry, ProvidersProxy>.clear() {
      _builder.clearProviders()
    }
  }
  @kotlin.jvm.JvmName("-initializeprovidersEntry")
  public inline fun providersEntry(block: agent.v1.ListProvidersCatalogResponseKt.ProvidersEntryKt.Dsl.() -> kotlin.Unit): agent.v1.ListProvidersCatalogResponse.ProvidersEntry =
    agent.v1.ListProvidersCatalogResponseKt.ProvidersEntryKt.Dsl._create(agent.v1.ListProvidersCatalogResponse.ProvidersEntry.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `agent.v1.ListProvidersCatalogResponse.ProvidersEntry`
   */
  public object ProvidersEntryKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: agent.v1.ListProvidersCatalogResponse.ProvidersEntry.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: agent.v1.ListProvidersCatalogResponse.ProvidersEntry.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): agent.v1.ListProvidersCatalogResponse.ProvidersEntry = _builder.build()

      /**
       * `string key = 1 [json_name = "key"];`
       */
      public var key: kotlin.String
        @kotlin.jvm.JvmName("getKey")
          get() = _builder.key
        @kotlin.jvm.JvmName("setKey")
          set(value) {
          _builder.key = value
        }
      /**
       * `string key = 1 [json_name = "key"];`
       */
      public fun clearKey() {
        _builder.clearKey()
      }

      /**
       * `.agent.v1.CatalogProvider value = 2 [json_name = "value"];`
       */
      public var value: agent.v1.CatalogProvider
        @kotlin.jvm.JvmName("getValue")
          get() = _builder.value
        @kotlin.jvm.JvmName("setValue")
          set(value) {
          _builder.value = value
        }
      /**
       * `.agent.v1.CatalogProvider value = 2 [json_name = "value"];`
       */
      public fun clearValue() {
        _builder.clearValue()
      }
      /**
       * `.agent.v1.CatalogProvider value = 2 [json_name = "value"];`
       * @return Whether the value field is set.
       */
      public fun hasValue(): kotlin.Boolean {
        return _builder.hasValue()
      }

      public val ProvidersEntryKt.Dsl.valueOrNull: agent.v1.CatalogProvider?
        get() = _builder.valueOrNull
    }
  }
}
public inline fun agent.v1.ListProvidersCatalogResponse.copy(block: `agent.v1`.ListProvidersCatalogResponseKt.Dsl.() -> kotlin.Unit): agent.v1.ListProvidersCatalogResponse =
  `agent.v1`.ListProvidersCatalogResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public inline fun agent.v1.ListProvidersCatalogResponse.ProvidersEntry.copy(block: `agent.v1`.ListProvidersCatalogResponseKt.ProvidersEntryKt.Dsl.() -> kotlin.Unit): agent.v1.ListProvidersCatalogResponse.ProvidersEntry =
  `agent.v1`.ListProvidersCatalogResponseKt.ProvidersEntryKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val agent.v1.ListProvidersCatalogResponse.ProvidersEntryOrBuilder.valueOrNull: agent.v1.CatalogProvider?
  get() = if (hasValue()) getValue() else null

