// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package agent.v1;

@kotlin.jvm.JvmName("-initializelistTenantsRequest")
public inline fun listTenantsRequest(block: agent.v1.ListTenantsRequestKt.Dsl.() -> kotlin.Unit): agent.v1.ListTenantsRequest =
  agent.v1.ListTenantsRequestKt.Dsl._create(agent.v1.ListTenantsRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `agent.v1.ListTenantsRequest`
 */
public object ListTenantsRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: agent.v1.ListTenantsRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: agent.v1.ListTenantsRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): agent.v1.ListTenantsRequest = _builder.build()
  }
}
public inline fun agent.v1.ListTenantsRequest.copy(block: `agent.v1`.ListTenantsRequestKt.Dsl.() -> kotlin.Unit): agent.v1.ListTenantsRequest =
  `agent.v1`.ListTenantsRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

