// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto
// Protobuf Java Version: 4.36.1

package agent.v1;

@com.google.protobuf.Generated
public interface ListProvidersCatalogResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agent.v1.ListProvidersCatalogResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .agent.v1.ListProvidersCatalogResponse.ProvidersEntry providers = 1 [json_name = "providers"];</code>
   */
  java.util.List<agent.v1.ListProvidersCatalogResponse.ProvidersEntry> 
      getProvidersList();
  /**
   * <code>repeated .agent.v1.ListProvidersCatalogResponse.ProvidersEntry providers = 1 [json_name = "providers"];</code>
   */
  agent.v1.ListProvidersCatalogResponse.ProvidersEntry getProviders(int index);
  /**
   * <code>repeated .agent.v1.ListProvidersCatalogResponse.ProvidersEntry providers = 1 [json_name = "providers"];</code>
   */
  int getProvidersCount();
}
