// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package agent.v1;

@kotlin.jvm.JvmName("-initializemodelVariant")
public inline fun modelVariant(block: agent.v1.ModelVariantKt.Dsl.() -> kotlin.Unit): agent.v1.ModelVariant =
  agent.v1.ModelVariantKt.Dsl._create(agent.v1.ModelVariant.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `agent.v1.ModelVariant`
 */
public object ModelVariantKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: agent.v1.ModelVariant.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: agent.v1.ModelVariant.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): agent.v1.ModelVariant = _builder.build()

    /**
     * `string id = 1 [json_name = "id"];`
     */
    public var id: kotlin.String
      @kotlin.jvm.JvmName("getId")
        get() = _builder.id
      @kotlin.jvm.JvmName("setId")
        set(value) {
        _builder.id = value
      }
    /**
     * `string id = 1 [json_name = "id"];`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `string name = 2 [json_name = "name"];`
     */
    public var name: kotlin.String
      @kotlin.jvm.JvmName("getName")
        get() = _builder.name
      @kotlin.jvm.JvmName("setName")
        set(value) {
        _builder.name = value
      }
    /**
     * `string name = 2 [json_name = "name"];`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `string description = 3 [json_name = "description"];`
     */
    public var description: kotlin.String
      @kotlin.jvm.JvmName("getDescription")
        get() = _builder.description
      @kotlin.jvm.JvmName("setDescription")
        set(value) {
        _builder.description = value
      }
    /**
     * `string description = 3 [json_name = "description"];`
     */
    public fun clearDescription() {
      _builder.clearDescription()
    }
  }
}
public inline fun agent.v1.ModelVariant.copy(block: `agent.v1`.ModelVariantKt.Dsl.() -> kotlin.Unit): agent.v1.ModelVariant =
  `agent.v1`.ModelVariantKt.Dsl._create(this.toBuilder()).apply { block() }._build()

