// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package agent.v1;

@kotlin.jvm.JvmName("-initializemodelInfo")
public inline fun modelInfo(block: agent.v1.ModelInfoKt.Dsl.() -> kotlin.Unit): agent.v1.ModelInfo =
  agent.v1.ModelInfoKt.Dsl._create(agent.v1.ModelInfo.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `agent.v1.ModelInfo`
 */
public object ModelInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: agent.v1.ModelInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: agent.v1.ModelInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): agent.v1.ModelInfo = _builder.build()

    /**
     * `string id = 1 [json_name = "id"];`
     */
    public var id: kotlin.String
      @kotlin.jvm.JvmName("getId")
        get() = _builder.id
      @kotlin.jvm.JvmName("setId")
        set(value) {
        _builder.id = value
      }
    /**
     * `string id = 1 [json_name = "id"];`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `string name = 2 [json_name = "name"];`
     */
    public var name: kotlin.String
      @kotlin.jvm.JvmName("getName")
        get() = _builder.name
      @kotlin.jvm.JvmName("setName")
        set(value) {
        _builder.name = value
      }
    /**
     * `string name = 2 [json_name = "name"];`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class VariantsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .agent.v1.ModelVariant variants = 3 [json_name = "variants"];`
     */
     public val variants: com.google.protobuf.kotlin.DslList<agent.v1.ModelVariant, VariantsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.variantsList
      )
    /**
     * `repeated .agent.v1.ModelVariant variants = 3 [json_name = "variants"];`
     * @param value The variants to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addVariants")
    public fun com.google.protobuf.kotlin.DslList<agent.v1.ModelVariant, VariantsProxy>.add(value: agent.v1.ModelVariant) {
      _builder.addVariants(value)
    }
    /**
     * `repeated .agent.v1.ModelVariant variants = 3 [json_name = "variants"];`
     * @param value The variants to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignVariants")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<agent.v1.ModelVariant, VariantsProxy>.plusAssign(value: agent.v1.ModelVariant) {
      add(value)
    }
    /**
     * `repeated .agent.v1.ModelVariant variants = 3 [json_name = "variants"];`
     * @param values The variants to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllVariants")
    public fun com.google.protobuf.kotlin.DslList<agent.v1.ModelVariant, VariantsProxy>.addAll(values: kotlin.collections.Iterable<agent.v1.ModelVariant>) {
      _builder.addAllVariants(values)
    }
    /**
     * `repeated .agent.v1.ModelVariant variants = 3 [json_name = "variants"];`
     * @param values The variants to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllVariants")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<agent.v1.ModelVariant, VariantsProxy>.plusAssign(values: kotlin.collections.Iterable<agent.v1.ModelVariant>) {
      addAll(values)
    }
    /**
     * `repeated .agent.v1.ModelVariant variants = 3 [json_name = "variants"];`
     * @param index The index to set the value at.
     * @param value The variants to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setVariants")
    public operator fun com.google.protobuf.kotlin.DslList<agent.v1.ModelVariant, VariantsProxy>.set(index: kotlin.Int, value: agent.v1.ModelVariant) {
      _builder.setVariants(index, value)
    }
    /**
     * `repeated .agent.v1.ModelVariant variants = 3 [json_name = "variants"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearVariants")
    public fun com.google.protobuf.kotlin.DslList<agent.v1.ModelVariant, VariantsProxy>.clear() {
      _builder.clearVariants()
    }

    /**
     * `int64 context_limit = 4 [json_name = "contextLimit"];`
     */
    public var contextLimit: kotlin.Long
      @kotlin.jvm.JvmName("getContextLimit")
        get() = _builder.contextLimit
      @kotlin.jvm.JvmName("setContextLimit")
        set(value) {
        _builder.contextLimit = value
      }
    /**
     * `int64 context_limit = 4 [json_name = "contextLimit"];`
     */
    public fun clearContextLimit() {
      _builder.clearContextLimit()
    }
  }
}
public inline fun agent.v1.ModelInfo.copy(block: `agent.v1`.ModelInfoKt.Dsl.() -> kotlin.Unit): agent.v1.ModelInfo =
  `agent.v1`.ModelInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

