// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto
// Protobuf Java Version: 4.36.1

package agent.v1;

@com.google.protobuf.Generated
public interface ModelInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agent.v1.ModelInfo)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>repeated .agent.v1.ModelVariant variants = 3 [json_name = "variants"];</code>
   */
  java.util.List<agent.v1.ModelVariant> 
      getVariantsList();
  /**
   * <code>repeated .agent.v1.ModelVariant variants = 3 [json_name = "variants"];</code>
   */
  agent.v1.ModelVariant getVariants(int index);
  /**
   * <code>repeated .agent.v1.ModelVariant variants = 3 [json_name = "variants"];</code>
   */
  int getVariantsCount();

  /**
   * <code>int64 context_limit = 4 [json_name = "contextLimit"];</code>
   * @return The contextLimit.
   */
  long getContextLimit();
}
