// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto
// Protobuf Java Version: 4.36.1

package agent.v1;

@com.google.protobuf.Generated
public interface PromptResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agent.v1.PromptResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string event = 1 [json_name = "event"];</code>
   * @return The event.
   */
  java.lang.String getEvent();
  /**
   * <code>string event = 1 [json_name = "event"];</code>
   * @return The bytes for event.
   */
  com.google.protobuf.ByteString
      getEventBytes();

  /**
   * <code>repeated .agent.v1.PromptResponse.ParamsEntry params = 2 [json_name = "params"];</code>
   */
  java.util.List<agent.v1.PromptResponse.ParamsEntry> 
      getParamsList();
  /**
   * <code>repeated .agent.v1.PromptResponse.ParamsEntry params = 2 [json_name = "params"];</code>
   */
  agent.v1.PromptResponse.ParamsEntry getParams(int index);
  /**
   * <code>repeated .agent.v1.PromptResponse.ParamsEntry params = 2 [json_name = "params"];</code>
   */
  int getParamsCount();

  /**
   * <code>string eid = 3 [json_name = "eid"];</code>
   * @return The eid.
   */
  java.lang.String getEid();
  /**
   * <code>string eid = 3 [json_name = "eid"];</code>
   * @return The bytes for eid.
   */
  com.google.protobuf.ByteString
      getEidBytes();
}
