// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto
// Protobuf Java Version: 4.36.1

package agent.v1;

@com.google.protobuf.Generated
public interface PromptResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agent.v1.PromptResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string event = 1 [json_name = "event"];</code>
   * @return The event.
   */
  java.lang.String getEvent();
  /**
   * <code>string event = 1 [json_name = "event"];</code>
   * @return The bytes for event.
   */
  com.google.protobuf.ByteString
      getEventBytes();

  /**
   * <code>map&lt;string, string&gt; params = 2 [json_name = "params"];</code>
   */
  int getParamsCount();
  /**
   * <code>map&lt;string, string&gt; params = 2 [json_name = "params"];</code>
   */
  boolean containsParams(
      java.lang.String key);
  /**
   * Use {@link #getParamsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getParams();
  /**
   * <code>map&lt;string, string&gt; params = 2 [json_name = "params"];</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getParamsMap();
  /**
   * <code>map&lt;string, string&gt; params = 2 [json_name = "params"];</code>
   */

  /* nullable */
java.lang.String getParamsOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; params = 2 [json_name = "params"];</code>
   */

  java.lang.String getParamsOrThrow(
      java.lang.String key);

  /**
   * <code>string eid = 3 [json_name = "eid"];</code>
   * @return The eid.
   */
  java.lang.String getEid();
  /**
   * <code>string eid = 3 [json_name = "eid"];</code>
   * @return The bytes for eid.
   */
  com.google.protobuf.ByteString
      getEidBytes();
}
