// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package agent.v1;

@kotlin.jvm.JvmName("-initializepromptResponse")
public inline fun promptResponse(block: agent.v1.PromptResponseKt.Dsl.() -> kotlin.Unit): agent.v1.PromptResponse =
  agent.v1.PromptResponseKt.Dsl._create(agent.v1.PromptResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `agent.v1.PromptResponse`
 */
public object PromptResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: agent.v1.PromptResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: agent.v1.PromptResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): agent.v1.PromptResponse = _builder.build()

    /**
     * `string event = 1 [json_name = "event"];`
     */
    public var event: kotlin.String
      @kotlin.jvm.JvmName("getEvent")
        get() = _builder.event
      @kotlin.jvm.JvmName("setEvent")
        set(value) {
        _builder.event = value
      }
    /**
     * `string event = 1 [json_name = "event"];`
     */
    public fun clearEvent() {
      _builder.clearEvent()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ParamsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .agent.v1.PromptResponse.ParamsEntry params = 2 [json_name = "params"];`
     */
     public val params: com.google.protobuf.kotlin.DslList<agent.v1.PromptResponse.ParamsEntry, ParamsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.paramsList
      )
    /**
     * `repeated .agent.v1.PromptResponse.ParamsEntry params = 2 [json_name = "params"];`
     * @param value The params to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addParams")
    public fun com.google.protobuf.kotlin.DslList<agent.v1.PromptResponse.ParamsEntry, ParamsProxy>.add(value: agent.v1.PromptResponse.ParamsEntry) {
      _builder.addParams(value)
    }
    /**
     * `repeated .agent.v1.PromptResponse.ParamsEntry params = 2 [json_name = "params"];`
     * @param value The params to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignParams")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<agent.v1.PromptResponse.ParamsEntry, ParamsProxy>.plusAssign(value: agent.v1.PromptResponse.ParamsEntry) {
      add(value)
    }
    /**
     * `repeated .agent.v1.PromptResponse.ParamsEntry params = 2 [json_name = "params"];`
     * @param values The params to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllParams")
    public fun com.google.protobuf.kotlin.DslList<agent.v1.PromptResponse.ParamsEntry, ParamsProxy>.addAll(values: kotlin.collections.Iterable<agent.v1.PromptResponse.ParamsEntry>) {
      _builder.addAllParams(values)
    }
    /**
     * `repeated .agent.v1.PromptResponse.ParamsEntry params = 2 [json_name = "params"];`
     * @param values The params to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllParams")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<agent.v1.PromptResponse.ParamsEntry, ParamsProxy>.plusAssign(values: kotlin.collections.Iterable<agent.v1.PromptResponse.ParamsEntry>) {
      addAll(values)
    }
    /**
     * `repeated .agent.v1.PromptResponse.ParamsEntry params = 2 [json_name = "params"];`
     * @param index The index to set the value at.
     * @param value The params to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setParams")
    public operator fun com.google.protobuf.kotlin.DslList<agent.v1.PromptResponse.ParamsEntry, ParamsProxy>.set(index: kotlin.Int, value: agent.v1.PromptResponse.ParamsEntry) {
      _builder.setParams(index, value)
    }
    /**
     * `repeated .agent.v1.PromptResponse.ParamsEntry params = 2 [json_name = "params"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearParams")
    public fun com.google.protobuf.kotlin.DslList<agent.v1.PromptResponse.ParamsEntry, ParamsProxy>.clear() {
      _builder.clearParams()
    }

    /**
     * `string eid = 3 [json_name = "eid"];`
     */
    public var eid: kotlin.String
      @kotlin.jvm.JvmName("getEid")
        get() = _builder.eid
      @kotlin.jvm.JvmName("setEid")
        set(value) {
        _builder.eid = value
      }
    /**
     * `string eid = 3 [json_name = "eid"];`
     */
    public fun clearEid() {
      _builder.clearEid()
    }
  }
  @kotlin.jvm.JvmName("-initializeparamsEntry")
  public inline fun paramsEntry(block: agent.v1.PromptResponseKt.ParamsEntryKt.Dsl.() -> kotlin.Unit): agent.v1.PromptResponse.ParamsEntry =
    agent.v1.PromptResponseKt.ParamsEntryKt.Dsl._create(agent.v1.PromptResponse.ParamsEntry.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `agent.v1.PromptResponse.ParamsEntry`
   */
  public object ParamsEntryKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: agent.v1.PromptResponse.ParamsEntry.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: agent.v1.PromptResponse.ParamsEntry.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): agent.v1.PromptResponse.ParamsEntry = _builder.build()

      /**
       * `string key = 1 [json_name = "key"];`
       */
      public var key: kotlin.String
        @kotlin.jvm.JvmName("getKey")
          get() = _builder.key
        @kotlin.jvm.JvmName("setKey")
          set(value) {
          _builder.key = value
        }
      /**
       * `string key = 1 [json_name = "key"];`
       */
      public fun clearKey() {
        _builder.clearKey()
      }

      /**
       * `string value = 2 [json_name = "value"];`
       */
      public var value: kotlin.String
        @kotlin.jvm.JvmName("getValue")
          get() = _builder.value
        @kotlin.jvm.JvmName("setValue")
          set(value) {
          _builder.value = value
        }
      /**
       * `string value = 2 [json_name = "value"];`
       */
      public fun clearValue() {
        _builder.clearValue()
      }
    }
  }
}
public inline fun agent.v1.PromptResponse.copy(block: `agent.v1`.PromptResponseKt.Dsl.() -> kotlin.Unit): agent.v1.PromptResponse =
  `agent.v1`.PromptResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public inline fun agent.v1.PromptResponse.ParamsEntry.copy(block: `agent.v1`.PromptResponseKt.ParamsEntryKt.Dsl.() -> kotlin.Unit): agent.v1.PromptResponse.ParamsEntry =
  `agent.v1`.PromptResponseKt.ParamsEntryKt.Dsl._create(this.toBuilder()).apply { block() }._build()

