// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package agent.v1;

@kotlin.jvm.JvmName("-initializeproviderModel")
public inline fun providerModel(block: agent.v1.ProviderModelKt.Dsl.() -> kotlin.Unit): agent.v1.ProviderModel =
  agent.v1.ProviderModelKt.Dsl._create(agent.v1.ProviderModel.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `agent.v1.ProviderModel`
 */
public object ProviderModelKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: agent.v1.ProviderModel.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: agent.v1.ProviderModel.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): agent.v1.ProviderModel = _builder.build()

    /**
     * `string id = 1 [json_name = "id"];`
     */
    public var id: kotlin.String
      @kotlin.jvm.JvmName("getId")
        get() = _builder.id
      @kotlin.jvm.JvmName("setId")
        set(value) {
        _builder.id = value
      }
    /**
     * `string id = 1 [json_name = "id"];`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `string name = 2 [json_name = "name"];`
     */
    public var name: kotlin.String
      @kotlin.jvm.JvmName("getName")
        get() = _builder.name
      @kotlin.jvm.JvmName("setName")
        set(value) {
        _builder.name = value
      }
    /**
     * `string name = 2 [json_name = "name"];`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * ```
     * required for non-gateway providers; 0 for gateway-classified kinds.
     * ```
     *
     * `int64 context_limit = 3 [json_name = "contextLimit"];`
     */
    public var contextLimit: kotlin.Long
      @kotlin.jvm.JvmName("getContextLimit")
        get() = _builder.contextLimit
      @kotlin.jvm.JvmName("setContextLimit")
        set(value) {
        _builder.contextLimit = value
      }
    /**
     * ```
     * required for non-gateway providers; 0 for gateway-classified kinds.
     * ```
     *
     * `int64 context_limit = 3 [json_name = "contextLimit"];`
     */
    public fun clearContextLimit() {
      _builder.clearContextLimit()
    }

    /**
     * ```
     * text | image | video | speech | transcription | embedding | reranking.
     * ```
     *
     * `string model_type = 4 [json_name = "modelType"];`
     */
    public var modelType: kotlin.String
      @kotlin.jvm.JvmName("getModelType")
        get() = _builder.modelType
      @kotlin.jvm.JvmName("setModelType")
        set(value) {
        _builder.modelType = value
      }
    /**
     * ```
     * text | image | video | speech | transcription | embedding | reranking.
     * ```
     *
     * `string model_type = 4 [json_name = "modelType"];`
     */
    public fun clearModelType() {
      _builder.clearModelType()
    }
  }
}
public inline fun agent.v1.ProviderModel.copy(block: `agent.v1`.ProviderModelKt.Dsl.() -> kotlin.Unit): agent.v1.ProviderModel =
  `agent.v1`.ProviderModelKt.Dsl._create(this.toBuilder()).apply { block() }._build()

