// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto
// Protobuf Java Version: 4.36.1

package agent.v1;

@com.google.protobuf.Generated
public interface ProviderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agent.v1.Provider)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string provider_id = 1 [json_name = "providerId"];</code>
   * @return The providerId.
   */
  java.lang.String getProviderId();
  /**
   * <code>string provider_id = 1 [json_name = "providerId"];</code>
   * @return The bytes for providerId.
   */
  com.google.protobuf.ByteString
      getProviderIdBytes();

  /**
   * <code>string api_type = 2 [json_name = "apiType"];</code>
   * @return The apiType.
   */
  java.lang.String getApiType();
  /**
   * <code>string api_type = 2 [json_name = "apiType"];</code>
   * @return The bytes for apiType.
   */
  com.google.protobuf.ByteString
      getApiTypeBytes();

  /**
   * <code>string base_url = 3 [json_name = "baseUrl"];</code>
   * @return The baseUrl.
   */
  java.lang.String getBaseUrl();
  /**
   * <code>string base_url = 3 [json_name = "baseUrl"];</code>
   * @return The bytes for baseUrl.
   */
  com.google.protobuf.ByteString
      getBaseUrlBytes();

  /**
   * <code>string api_key = 4 [json_name = "apiKey"];</code>
   * @return The apiKey.
   */
  java.lang.String getApiKey();
  /**
   * <code>string api_key = 4 [json_name = "apiKey"];</code>
   * @return The bytes for apiKey.
   */
  com.google.protobuf.ByteString
      getApiKeyBytes();

  /**
   * <code>repeated .agent.v1.Provider.HeadersEntry headers = 5 [json_name = "headers"];</code>
   */
  java.util.List<agent.v1.Provider.HeadersEntry> 
      getHeadersList();
  /**
   * <code>repeated .agent.v1.Provider.HeadersEntry headers = 5 [json_name = "headers"];</code>
   */
  agent.v1.Provider.HeadersEntry getHeaders(int index);
  /**
   * <code>repeated .agent.v1.Provider.HeadersEntry headers = 5 [json_name = "headers"];</code>
   */
  int getHeadersCount();

  /**
   * <code>repeated .agent.v1.ProviderModel models = 6 [json_name = "models"];</code>
   */
  java.util.List<agent.v1.ProviderModel> 
      getModelsList();
  /**
   * <code>repeated .agent.v1.ProviderModel models = 6 [json_name = "models"];</code>
   */
  agent.v1.ProviderModel getModels(int index);
  /**
   * <code>repeated .agent.v1.ProviderModel models = 6 [json_name = "models"];</code>
   */
  int getModelsCount();

  /**
   * <code>string updated_at = 7 [json_name = "updatedAt"];</code>
   * @return The updatedAt.
   */
  java.lang.String getUpdatedAt();
  /**
   * <code>string updated_at = 7 [json_name = "updatedAt"];</code>
   * @return The bytes for updatedAt.
   */
  com.google.protobuf.ByteString
      getUpdatedAtBytes();
}
