// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package agent.v1;

@kotlin.jvm.JvmName("-initializerevokeTenantTokenResponse")
public inline fun revokeTenantTokenResponse(block: agent.v1.RevokeTenantTokenResponseKt.Dsl.() -> kotlin.Unit): agent.v1.RevokeTenantTokenResponse =
  agent.v1.RevokeTenantTokenResponseKt.Dsl._create(agent.v1.RevokeTenantTokenResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `agent.v1.RevokeTenantTokenResponse`
 */
public object RevokeTenantTokenResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: agent.v1.RevokeTenantTokenResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: agent.v1.RevokeTenantTokenResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): agent.v1.RevokeTenantTokenResponse = _builder.build()

    /**
     * `bool ok = 1 [json_name = "ok"];`
     */
    public var ok: kotlin.Boolean
      @kotlin.jvm.JvmName("getOk")
        get() = _builder.ok
      @kotlin.jvm.JvmName("setOk")
        set(value) {
        _builder.ok = value
      }
    /**
     * `bool ok = 1 [json_name = "ok"];`
     */
    public fun clearOk() {
      _builder.clearOk()
    }
  }
}
public inline fun agent.v1.RevokeTenantTokenResponse.copy(block: `agent.v1`.RevokeTenantTokenResponseKt.Dsl.() -> kotlin.Unit): agent.v1.RevokeTenantTokenResponse =
  `agent.v1`.RevokeTenantTokenResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

