// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package agent.v1;

@kotlin.jvm.JvmName("-initializerevokeTenantTokenRequest")
public inline fun revokeTenantTokenRequest(block: agent.v1.RevokeTenantTokenRequestKt.Dsl.() -> kotlin.Unit): agent.v1.RevokeTenantTokenRequest =
  agent.v1.RevokeTenantTokenRequestKt.Dsl._create(agent.v1.RevokeTenantTokenRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `agent.v1.RevokeTenantTokenRequest`
 */
public object RevokeTenantTokenRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: agent.v1.RevokeTenantTokenRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: agent.v1.RevokeTenantTokenRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): agent.v1.RevokeTenantTokenRequest = _builder.build()

    /**
     * `string token_id = 1 [json_name = "tokenId"];`
     */
    public var tokenId: kotlin.String
      @kotlin.jvm.JvmName("getTokenId")
        get() = _builder.tokenId
      @kotlin.jvm.JvmName("setTokenId")
        set(value) {
        _builder.tokenId = value
      }
    /**
     * `string token_id = 1 [json_name = "tokenId"];`
     */
    public fun clearTokenId() {
      _builder.clearTokenId()
    }
  }
}
public inline fun agent.v1.RevokeTenantTokenRequest.copy(block: `agent.v1`.RevokeTenantTokenRequestKt.Dsl.() -> kotlin.Unit): agent.v1.RevokeTenantTokenRequest =
  `agent.v1`.RevokeTenantTokenRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

