// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package agent.v1;

@kotlin.jvm.JvmName("-initializerotateTenantTokenResponse")
public inline fun rotateTenantTokenResponse(block: agent.v1.RotateTenantTokenResponseKt.Dsl.() -> kotlin.Unit): agent.v1.RotateTenantTokenResponse =
  agent.v1.RotateTenantTokenResponseKt.Dsl._create(agent.v1.RotateTenantTokenResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `agent.v1.RotateTenantTokenResponse`
 */
public object RotateTenantTokenResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: agent.v1.RotateTenantTokenResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: agent.v1.RotateTenantTokenResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): agent.v1.RotateTenantTokenResponse = _builder.build()

    /**
     * `.agent.v1.TenantToken token = 1 [json_name = "token"];`
     */
    public var token: agent.v1.TenantToken
      @kotlin.jvm.JvmName("getToken")
        get() = _builder.token
      @kotlin.jvm.JvmName("setToken")
        set(value) {
        _builder.token = value
      }
    /**
     * `.agent.v1.TenantToken token = 1 [json_name = "token"];`
     */
    public fun clearToken() {
      _builder.clearToken()
    }
    /**
     * `.agent.v1.TenantToken token = 1 [json_name = "token"];`
     * @return Whether the token field is set.
     */
    public fun hasToken(): kotlin.Boolean {
      return _builder.hasToken()
    }

    public val RotateTenantTokenResponseKt.Dsl.tokenOrNull: agent.v1.TenantToken?
      get() = _builder.tokenOrNull

    /**
     * `string plaintext = 2 [json_name = "plaintext"];`
     */
    public var plaintext: kotlin.String
      @kotlin.jvm.JvmName("getPlaintext")
        get() = _builder.plaintext
      @kotlin.jvm.JvmName("setPlaintext")
        set(value) {
        _builder.plaintext = value
      }
    /**
     * `string plaintext = 2 [json_name = "plaintext"];`
     */
    public fun clearPlaintext() {
      _builder.clearPlaintext()
    }
  }
}
public inline fun agent.v1.RotateTenantTokenResponse.copy(block: `agent.v1`.RotateTenantTokenResponseKt.Dsl.() -> kotlin.Unit): agent.v1.RotateTenantTokenResponse =
  `agent.v1`.RotateTenantTokenResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val agent.v1.RotateTenantTokenResponseOrBuilder.tokenOrNull: agent.v1.TenantToken?
  get() = if (hasToken()) getToken() else null

