// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto
// Protobuf Java Version: 4.36.1

package agent.v1;

@com.google.protobuf.Generated
public interface RotateTenantTokenResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agent.v1.RotateTenantTokenResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.agent.v1.TenantToken token = 1 [json_name = "token"];</code>
   * @return Whether the token field is set.
   */
  boolean hasToken();
  /**
   * <code>.agent.v1.TenantToken token = 1 [json_name = "token"];</code>
   * @return The token.
   */
  agent.v1.TenantToken getToken();

  /**
   * <code>string plaintext = 2 [json_name = "plaintext"];</code>
   * @return The plaintext.
   */
  java.lang.String getPlaintext();
  /**
   * <code>string plaintext = 2 [json_name = "plaintext"];</code>
   * @return The bytes for plaintext.
   */
  com.google.protobuf.ByteString
      getPlaintextBytes();
}
