// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto
// Protobuf Java Version: 4.36.1

package agent.v1;

@com.google.protobuf.Generated
public interface ToolConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agent.v1.ToolConfig)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .agent.v1.ToolConfig.ValuesEntry values = 1 [json_name = "values"];</code>
   */
  java.util.List<agent.v1.ToolConfig.ValuesEntry> 
      getValuesList();
  /**
   * <code>repeated .agent.v1.ToolConfig.ValuesEntry values = 1 [json_name = "values"];</code>
   */
  agent.v1.ToolConfig.ValuesEntry getValues(int index);
  /**
   * <code>repeated .agent.v1.ToolConfig.ValuesEntry values = 1 [json_name = "values"];</code>
   */
  int getValuesCount();
}
