// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package agent.v1;

@kotlin.jvm.JvmName("-initializeupdateTenantResponse")
public inline fun updateTenantResponse(block: agent.v1.UpdateTenantResponseKt.Dsl.() -> kotlin.Unit): agent.v1.UpdateTenantResponse =
  agent.v1.UpdateTenantResponseKt.Dsl._create(agent.v1.UpdateTenantResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `agent.v1.UpdateTenantResponse`
 */
public object UpdateTenantResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: agent.v1.UpdateTenantResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: agent.v1.UpdateTenantResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): agent.v1.UpdateTenantResponse = _builder.build()

    /**
     * `.agent.v1.Tenant tenant = 1 [json_name = "tenant"];`
     */
    public var tenant: agent.v1.Tenant
      @kotlin.jvm.JvmName("getTenant")
        get() = _builder.tenant
      @kotlin.jvm.JvmName("setTenant")
        set(value) {
        _builder.tenant = value
      }
    /**
     * `.agent.v1.Tenant tenant = 1 [json_name = "tenant"];`
     */
    public fun clearTenant() {
      _builder.clearTenant()
    }
    /**
     * `.agent.v1.Tenant tenant = 1 [json_name = "tenant"];`
     * @return Whether the tenant field is set.
     */
    public fun hasTenant(): kotlin.Boolean {
      return _builder.hasTenant()
    }

    public val UpdateTenantResponseKt.Dsl.tenantOrNull: agent.v1.Tenant?
      get() = _builder.tenantOrNull
  }
}
public inline fun agent.v1.UpdateTenantResponse.copy(block: `agent.v1`.UpdateTenantResponseKt.Dsl.() -> kotlin.Unit): agent.v1.UpdateTenantResponse =
  `agent.v1`.UpdateTenantResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val agent.v1.UpdateTenantResponseOrBuilder.tenantOrNull: agent.v1.Tenant?
  get() = if (hasTenant()) getTenant() else null

