// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto
// Protobuf Java Version: 4.36.1

package agent.v1;

@com.google.protobuf.Generated
public interface WatchSessionsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agent.v1.WatchSessionsResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .agent.v1.Session upserts = 1 [json_name = "upserts"];</code>
   */
  java.util.List<agent.v1.Session> 
      getUpsertsList();
  /**
   * <code>repeated .agent.v1.Session upserts = 1 [json_name = "upserts"];</code>
   */
  agent.v1.Session getUpserts(int index);
  /**
   * <code>repeated .agent.v1.Session upserts = 1 [json_name = "upserts"];</code>
   */
  int getUpsertsCount();

  /**
   * <code>repeated string removed = 2 [json_name = "removed"];</code>
   * @return A list containing the removed.
   */
  java.util.List<java.lang.String>
      getRemovedList();
  /**
   * <code>repeated string removed = 2 [json_name = "removed"];</code>
   * @return The count of removed.
   */
  int getRemovedCount();
  /**
   * <code>repeated string removed = 2 [json_name = "removed"];</code>
   * @param index The index of the element to return.
   * @return The removed at the given index.
   */
  java.lang.String getRemoved(int index);
  /**
   * <code>repeated string removed = 2 [json_name = "removed"];</code>
   * @param index The index of the element to return.
   * @return The removed at the given index.
   */
  com.google.protobuf.ByteString
      getRemovedBytes(int index);

  /**
   * <code>bool snapshot = 3 [json_name = "snapshot"];</code>
   * @return The snapshot.
   */
  boolean getSnapshot();
}
