// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package agent.v1;

@kotlin.jvm.JvmName("-initializewatchSessionRequest")
public inline fun watchSessionRequest(block: agent.v1.WatchSessionRequestKt.Dsl.() -> kotlin.Unit): agent.v1.WatchSessionRequest =
  agent.v1.WatchSessionRequestKt.Dsl._create(agent.v1.WatchSessionRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `agent.v1.WatchSessionRequest`
 */
public object WatchSessionRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: agent.v1.WatchSessionRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: agent.v1.WatchSessionRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): agent.v1.WatchSessionRequest = _builder.build()

    /**
     * `string id = 1 [json_name = "id"];`
     */
    public var id: kotlin.String
      @kotlin.jvm.JvmName("getId")
        get() = _builder.id
      @kotlin.jvm.JvmName("setId")
        set(value) {
        _builder.id = value
      }
    /**
     * `string id = 1 [json_name = "id"];`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `string since = 2 [json_name = "since"];`
     */
    public var since: kotlin.String
      @kotlin.jvm.JvmName("getSince")
        get() = _builder.since
      @kotlin.jvm.JvmName("setSince")
        set(value) {
        _builder.since = value
      }
    /**
     * `string since = 2 [json_name = "since"];`
     */
    public fun clearSince() {
      _builder.clearSince()
    }
  }
}
public inline fun agent.v1.WatchSessionRequest.copy(block: `agent.v1`.WatchSessionRequestKt.Dsl.() -> kotlin.Unit): agent.v1.WatchSessionRequest =
  `agent.v1`.WatchSessionRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

