// Code generated by protoc-gen-easyrpc-kotlin. DO NOT EDIT.
package agentsdk

import easyrpc.*
import agent.v1.*
import pbandk.decodeFromByteArray
import pbandk.encodeToByteArray
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow

class AgentServiceClient(private val t: Transport) {
  var lastTrailers: Map<String, List<String>> = emptyMap()
  suspend fun health(req: HealthRequest): HealthResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/Health", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return HealthResponse.decodeFromByteArray(res.body)
  }

  suspend fun listSessions(req: ListSessionsRequest): ListSessionsResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/ListSessions", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return ListSessionsResponse.decodeFromByteArray(res.body)
  }

  suspend fun createSession(req: CreateSessionRequest): CreateSessionResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/CreateSession", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return CreateSessionResponse.decodeFromByteArray(res.body)
  }

  suspend fun getSession(req: GetSessionRequest): GetSessionResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/GetSession", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return GetSessionResponse.decodeFromByteArray(res.body)
  }

  suspend fun deleteSession(req: DeleteSessionRequest): DeleteSessionResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/DeleteSession", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return DeleteSessionResponse.decodeFromByteArray(res.body)
  }

  suspend fun listMessages(req: ListMessagesRequest): ListMessagesResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/ListMessages", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return ListMessagesResponse.decodeFromByteArray(res.body)
  }

  fun prompt(req: PromptRequest): Flow<PromptResponse> = flow {
    val st = t.openStream(Request(url = "/agent.v1.AgentService/Prompt", body = frame(req.encodeToByteArray())))
    while (true) { val p = st.recv() ?: break; emit(PromptResponse.decodeFromByteArray(p)) }
    st.lastError()?.let { throw it }
  }

  fun watchSession(req: WatchSessionRequest): Flow<WatchSessionResponse> = flow {
    val st = t.openStream(Request(url = "/agent.v1.AgentService/WatchSession", body = frame(req.encodeToByteArray())))
    while (true) { val p = st.recv() ?: break; emit(WatchSessionResponse.decodeFromByteArray(p)) }
    st.lastError()?.let { throw it }
  }

  fun watchSessions(req: WatchSessionsRequest): Flow<WatchSessionsResponse> = flow {
    val st = t.openStream(Request(url = "/agent.v1.AgentService/WatchSessions", body = frame(req.encodeToByteArray())))
    while (true) { val p = st.recv() ?: break; emit(WatchSessionsResponse.decodeFromByteArray(p)) }
    st.lastError()?.let { throw it }
  }

  suspend fun fork(req: ForkRequest): ForkResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/Fork", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return ForkResponse.decodeFromByteArray(res.body)
  }

  suspend fun rename(req: RenameRequest): RenameResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/Rename", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return RenameResponse.decodeFromByteArray(res.body)
  }

  suspend fun setModel(req: SetModelRequest): SetModelResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/SetModel", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return SetModelResponse.decodeFromByteArray(res.body)
  }

  suspend fun undo(req: UndoRequest): UndoResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/Undo", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return UndoResponse.decodeFromByteArray(res.body)
  }

  suspend fun state(req: StateRequest): StateResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/State", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return StateResponse.decodeFromByteArray(res.body)
  }

  suspend fun mailbox(req: MailboxRequest): MailboxResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/Mailbox", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return MailboxResponse.decodeFromByteArray(res.body)
  }

  suspend fun updateSettings(req: UpdateSettingsRequest): UpdateSettingsResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/UpdateSettings", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return UpdateSettingsResponse.decodeFromByteArray(res.body)
  }

  suspend fun interrupt(req: InterruptRequest): InterruptResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/Interrupt", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return InterruptResponse.decodeFromByteArray(res.body)
  }

  suspend fun compact(req: CompactRequest): CompactResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/Compact", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return CompactResponse.decodeFromByteArray(res.body)
  }

  suspend fun listProviders(req: ListProvidersRequest): ListProvidersResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/ListProviders", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return ListProvidersResponse.decodeFromByteArray(res.body)
  }

  suspend fun listProvidersCatalog(req: ListProvidersCatalogRequest): ListProvidersCatalogResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/ListProvidersCatalog", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return ListProvidersCatalogResponse.decodeFromByteArray(res.body)
  }

  suspend fun registerProvider(req: RegisterProviderRequest): RegisterProviderResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/RegisterProvider", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return RegisterProviderResponse.decodeFromByteArray(res.body)
  }

  suspend fun deleteProvider(req: DeleteProviderRequest): DeleteProviderResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/DeleteProvider", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return DeleteProviderResponse.decodeFromByteArray(res.body)
  }

  suspend fun testProvider(req: TestProviderRequest): TestProviderResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/TestProvider", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return TestProviderResponse.decodeFromByteArray(res.body)
  }

  suspend fun listModels(req: ListModelsRequest): ListModelsResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/ListModels", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return ListModelsResponse.decodeFromByteArray(res.body)
  }

  suspend fun listPresets(req: ListPresetsRequest): ListPresetsResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/ListPresets", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return ListPresetsResponse.decodeFromByteArray(res.body)
  }

  suspend fun upsertPreset(req: UpsertPresetRequest): UpsertPresetResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/UpsertPreset", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return UpsertPresetResponse.decodeFromByteArray(res.body)
  }

  suspend fun deletePreset(req: DeletePresetRequest): DeletePresetResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/DeletePreset", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return DeletePresetResponse.decodeFromByteArray(res.body)
  }

  suspend fun previewPreset(req: PreviewPresetRequest): PreviewPresetResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/PreviewPreset", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return PreviewPresetResponse.decodeFromByteArray(res.body)
  }

  suspend fun getConfig(req: GetConfigRequest): GetConfigResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/GetConfig", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return GetConfigResponse.decodeFromByteArray(res.body)
  }

  suspend fun setConfig(req: SetConfigRequest): SetConfigResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/SetConfig", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return SetConfigResponse.decodeFromByteArray(res.body)
  }

  suspend fun listTools(req: ListToolsRequest): ListToolsResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/ListTools", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return ListToolsResponse.decodeFromByteArray(res.body)
  }

  suspend fun getToolConfig(req: GetToolConfigRequest): GetToolConfigResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/GetToolConfig", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return GetToolConfigResponse.decodeFromByteArray(res.body)
  }

  suspend fun setToolConfig(req: SetToolConfigRequest): SetToolConfigResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/SetToolConfig", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return SetToolConfigResponse.decodeFromByteArray(res.body)
  }

  suspend fun setExtensionConfig(req: SetExtensionConfigRequest): SetExtensionConfigResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/SetExtensionConfig", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return SetExtensionConfigResponse.decodeFromByteArray(res.body)
  }

  suspend fun uploadFile(req: UploadFileRequest): UploadFileResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/UploadFile", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return UploadFileResponse.decodeFromByteArray(res.body)
  }

  suspend fun ingestFile(req: IngestFileRequest): IngestFileResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/IngestFile", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return IngestFileResponse.decodeFromByteArray(res.body)
  }

  suspend fun getFile(req: GetFileRequest): GetFileResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/GetFile", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return GetFileResponse.decodeFromByteArray(res.body)
  }

  suspend fun getFileMeta(req: GetFileMetaRequest): GetFileMetaResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/GetFileMeta", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return GetFileMetaResponse.decodeFromByteArray(res.body)
  }

  suspend fun getAgentConfig(req: GetAgentConfigRequest): GetAgentConfigResponse {
    val res = t.send(Request(url = "/agent.v1.AgentService/GetAgentConfig", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return GetAgentConfigResponse.decodeFromByteArray(res.body)
  }

}