// Code generated by protoc-gen-easyrpc-kotlin. DO NOT EDIT.
package agentsdk

import easyrpc.*
import agent.v1.*
import pbandk.decodeFromByteArray
import pbandk.encodeToByteArray
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow

class AdminServiceClient(private val t: Transport) {
  var lastTrailers: Map<String, List<String>> = emptyMap()
  suspend fun listTenants(req: ListTenantsRequest): ListTenantsResponse {
    val res = t.send(Request(url = "/agent.v1.AdminService/ListTenants", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return ListTenantsResponse.decodeFromByteArray(res.body)
  }

  suspend fun createTenant(req: CreateTenantRequest): CreateTenantResponse {
    val res = t.send(Request(url = "/agent.v1.AdminService/CreateTenant", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return CreateTenantResponse.decodeFromByteArray(res.body)
  }

  suspend fun updateTenant(req: UpdateTenantRequest): UpdateTenantResponse {
    val res = t.send(Request(url = "/agent.v1.AdminService/UpdateTenant", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return UpdateTenantResponse.decodeFromByteArray(res.body)
  }

  suspend fun deleteTenant(req: DeleteTenantRequest): DeleteTenantResponse {
    val res = t.send(Request(url = "/agent.v1.AdminService/DeleteTenant", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return DeleteTenantResponse.decodeFromByteArray(res.body)
  }

  suspend fun issueTenantToken(req: IssueTenantTokenRequest): IssueTenantTokenResponse {
    val res = t.send(Request(url = "/agent.v1.AdminService/IssueTenantToken", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return IssueTenantTokenResponse.decodeFromByteArray(res.body)
  }

  suspend fun listTenantTokens(req: ListTenantTokensRequest): ListTenantTokensResponse {
    val res = t.send(Request(url = "/agent.v1.AdminService/ListTenantTokens", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return ListTenantTokensResponse.decodeFromByteArray(res.body)
  }

  suspend fun revokeTenantToken(req: RevokeTenantTokenRequest): RevokeTenantTokenResponse {
    val res = t.send(Request(url = "/agent.v1.AdminService/RevokeTenantToken", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return RevokeTenantTokenResponse.decodeFromByteArray(res.body)
  }

  suspend fun rotateTenantToken(req: RotateTenantTokenRequest): RotateTenantTokenResponse {
    val res = t.send(Request(url = "/agent.v1.AdminService/RotateTenantToken", body = req.encodeToByteArray()))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return RotateTenantTokenResponse.decodeFromByteArray(res.body)
  }

}