// Code generated by protoc-gen-easyrpc-kotlin. DO NOT EDIT.
package agentsdk

import easyrpc.*
import agent.v1.*
import pbandk.decodeFromByteArray
import pbandk.encodeToByteArray
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow

class AdminServiceClient(private val t: Transport) {
  var lastTrailers: Map<String, List<String>> = emptyMap()
  suspend fun listTenants(req: ListTenantsRequest, kind: String = KIND_PROTO): ListTenantsResponse {
    val ct = contentTypeFor(false, kind)
    val res = t.send(Request(url = "/agent.v1.AdminService/ListTenants", headers = mapOf("content-type" to listOf(ct)), body = encodeMsg(req, kind)))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return decodeMsg(res.body, ListTenantsResponse.Companion, kind)
  }

  suspend fun createTenant(req: CreateTenantRequest, kind: String = KIND_PROTO): CreateTenantResponse {
    val ct = contentTypeFor(false, kind)
    val res = t.send(Request(url = "/agent.v1.AdminService/CreateTenant", headers = mapOf("content-type" to listOf(ct)), body = encodeMsg(req, kind)))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return decodeMsg(res.body, CreateTenantResponse.Companion, kind)
  }

  suspend fun updateTenant(req: UpdateTenantRequest, kind: String = KIND_PROTO): UpdateTenantResponse {
    val ct = contentTypeFor(false, kind)
    val res = t.send(Request(url = "/agent.v1.AdminService/UpdateTenant", headers = mapOf("content-type" to listOf(ct)), body = encodeMsg(req, kind)))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return decodeMsg(res.body, UpdateTenantResponse.Companion, kind)
  }

  suspend fun deleteTenant(req: DeleteTenantRequest, kind: String = KIND_PROTO): DeleteTenantResponse {
    val ct = contentTypeFor(false, kind)
    val res = t.send(Request(url = "/agent.v1.AdminService/DeleteTenant", headers = mapOf("content-type" to listOf(ct)), body = encodeMsg(req, kind)))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return decodeMsg(res.body, DeleteTenantResponse.Companion, kind)
  }

  suspend fun issueTenantToken(req: IssueTenantTokenRequest, kind: String = KIND_PROTO): IssueTenantTokenResponse {
    val ct = contentTypeFor(false, kind)
    val res = t.send(Request(url = "/agent.v1.AdminService/IssueTenantToken", headers = mapOf("content-type" to listOf(ct)), body = encodeMsg(req, kind)))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return decodeMsg(res.body, IssueTenantTokenResponse.Companion, kind)
  }

  suspend fun listTenantTokens(req: ListTenantTokensRequest, kind: String = KIND_PROTO): ListTenantTokensResponse {
    val ct = contentTypeFor(false, kind)
    val res = t.send(Request(url = "/agent.v1.AdminService/ListTenantTokens", headers = mapOf("content-type" to listOf(ct)), body = encodeMsg(req, kind)))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return decodeMsg(res.body, ListTenantTokensResponse.Companion, kind)
  }

  suspend fun revokeTenantToken(req: RevokeTenantTokenRequest, kind: String = KIND_PROTO): RevokeTenantTokenResponse {
    val ct = contentTypeFor(false, kind)
    val res = t.send(Request(url = "/agent.v1.AdminService/RevokeTenantToken", headers = mapOf("content-type" to listOf(ct)), body = encodeMsg(req, kind)))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return decodeMsg(res.body, RevokeTenantTokenResponse.Companion, kind)
  }

  suspend fun rotateTenantToken(req: RotateTenantTokenRequest, kind: String = KIND_PROTO): RotateTenantTokenResponse {
    val ct = contentTypeFor(false, kind)
    val res = t.send(Request(url = "/agent.v1.AdminService/RotateTenantToken", headers = mapOf("content-type" to listOf(ct)), body = encodeMsg(req, kind)))
    res.error?.let{ throw it }
    lastTrailers = res.trailers
    return decodeMsg(res.body, RotateTenantTokenResponse.Companion, kind)
  }

}